init python:

    #MOVEDEX
    #movedex/      Name/Type/Category/Contest/PP/Power/Accuracy/Effect/Description
    #      0          1    2        3       4  5     6        7      8           9

    def GetMove(name):
        for num in range(0, len(movedex)):
            if (movedex[num][DexMacros.Name] == name):
                moveentry = movedex[num]
                return Move(moveentry[0], moveentry[1], moveentry[2], moveentry[3], moveentry[4], moveentry[5], moveentry[6], moveentry[7], moveentry[8], moveentry[9])
        return Move(999, "ERROR", "Bug", "Physical", "Smart", 20, 60, 5, -1, "This move should not show up. If it does, let me know.")

    def GetStartingMoves(pkmn):
        finalmoves = []
        newmoves = GetLevelMoves(pkmn, 5)[-4:]
        for possiblemove in newmoves:
            moveobj = GetMove(possiblemove[1])
            movepower = moveobj.Power
            if (isinstance(movepower, str) or movepower <= 70):
                finalmoves.append(moveobj)

        return finalmoves

    def GetMovesForLevel(pkmn):
        finalmoves = []
        finalmovestrings = []
        newmoves = GetLevelMoves(pkmn, pkmn.GetLevel())[-4:]
        for possiblemove in newmoves:
            movename = possiblemove[1]
            if (movename not in finalmovestrings):
                moveobj = GetMove(movename)
                finalmoves.append(moveobj)
                finalmovestrings.append(movename)

        return finalmoves

    movedex = []
    movedex.append([1,"Pound","Normal","Physical","Tough",35,40,1,0,"A damaging attack."])
    movedex.append([2,"Karate Chop","Fighting","Physical","Tough",25,50,1,-1,"High critical hit ratio."])
    movedex.append([3,"Double Slap","Normal","Physical","Cute",10,15,0.85,-1,"Hits 2-5 times in one turn."])
    movedex.append([4,"Comet Punch","Normal","Physical","Tough",15,18,0.85,-1,"Hits 2-5 times in one turn."])
    movedex.append([5,"Mega Punch","Normal","Physical","Tough",20,80,0.85,0,"A damaging attack."])
    movedex.append([6,"Pay Day","Normal","Physical","Clever",20,40,1,-1,"A small amount of money is gained after the battle resolves."])
    movedex.append([7,"Fire Punch","Fire","Physical","Tough",15,75,1,-1,"May burn opponent."])
    movedex.append([8,"Ice Punch","Ice","Physical","Beautiful",15,75,1,-1,"May freeze opponent."])
    movedex.append([9,"Thunder Punch","Electric","Physical","Cool",15,75,1,-1,"May paralyze opponent."])
    movedex.append([10,"Scratch","Normal","Physical","Tough",35,40,1,0,"A damaging attack."])
    movedex.append([11,"Vise Grip","Normal","Physical","Tough",30,55,1,0,"A damaging attack."])
    movedex.append([12,"Guillotine","Normal","Physical","Cool",5,0,"~",-1,"One-Hit-KO, if it hits."])
    movedex.append([13,"Razor Wind","Normal","Special","Cool",10,80,1,-1,"Charges on first turn, attacks on second. High critical hit ratio."])
    movedex.append([14,"Swords Dance","Normal","Status","Beautiful",20,0,"—",-1,"Sharply raises user's Attack."])
    movedex.append([15,"Cut","Normal","Physical","Cool",30,50,0.95,0,"A damaging attack."])
    movedex.append([16,"Gust","Flying","Special","Clever",35,40,1,-1,"Hits Pokémon using Fly/Bounce with double power."])
    movedex.append([17,"Wing Attack","Flying","Physical","Cool",35,60,1,0,"A damaging attack."])
    movedex.append([18,"Whirlwind","Normal","Status","Clever",20,0,1,-1,"In battles, the opponent switches. In the wild, the Pokémon runs."])
    movedex.append([19,"Fly","Flying","Physical","Clever",15,90,0.95,-1,"Flies up on first turn, attacks on second turn."])
    movedex.append([20,"Bind","Normal","Physical","Tough",20,15,.85,-1,"Traps opponent, damaging them for 4-5 turns."])
    movedex.append([21,"Slam","Normal","Physical","Tough",20,80,0.75,0,"A damaging attack."])
    movedex.append([22,"Vine Whip","Grass","Physical","Cool",25,45,1,0,"A damaging attack."])
    movedex.append([23,"Stomp","Normal","Physical","Tough",20,65,1,-1,"May cause flinching. Double damage against Minimized opponents."])
    movedex.append([24,"Double Kick","Fighting","Physical","Cool",30,30,1,-1,"Hits twice in one turn."])
    movedex.append([25,"Mega Kick","Normal","Physical","Cool",5,120,0.75,0,"A damaging attack."])
    movedex.append([26,"Jump Kick","Fighting","Physical","Cool",10,100,0.95,-1,"If it misses, the user loses half their HP."])
    movedex.append([27,"Rolling Kick","Fighting","Physical","Cool",15,60,0.85,-1,"May cause flinching."])
    movedex.append([28,"Sand Attack","Ground","Status","Cute",15,0,1,-1,"Lowers opponent's Accuracy."])
    movedex.append([29,"Headbutt","Normal","Physical","Tough",15,70,1,-1,"May cause flinching."])
    movedex.append([30,"Horn Attack","Normal","Physical","Cool",25,65,1,0,"A damaging attack."])
    movedex.append([31,"Fury Attack","Normal","Physical","Cool",20,15,0.85,-1,"Hits 2-5 times in one turn."])
    movedex.append([32,"Horn Drill","Normal","Physical","Cool",5,0,"~",-1,"One-Hit-KO, if it hits."])
    movedex.append([33,"Tackle","Normal","Physical","Tough",35,40,1,0,"A damaging attack."])
    movedex.append([34,"Body Slam","Normal","Physical","Tough",15,85,1,-1,"May paralyze opponent."])
    movedex.append([35,"Wrap","Normal","Physical","Tough",20,15,.9,-1,"Traps opponent, damaging them for 4-5 turns."])
    movedex.append([36,"Take Down","Normal","Physical","Tough",20,90,0.85,-1,"User receives recoil damage."])
    movedex.append([37,"Thrash","Normal","Physical","Tough",10,120,1,4,"User attacks for 2-3 turns but then becomes confused."])
    movedex.append([38,"Double-Edge","Normal","Physical","Tough",15,120,1,-1,"User receives recoil damage."])
    movedex.append([39,"Tail Whip","Normal","Status","Cute",30,0,"-","","Lowers opponent's Defense."])
    movedex.append([40,"Poison Sting","Poison","Physical","Clever",35,15,1,-1,"May poison the opponent."])
    movedex.append([41,"Twineedle","Bug","Physical","Cool",20,25,1,-1,"Hits twice in one turn. May poison opponent."])
    movedex.append([42,"Pin Missile","Bug","Physical","Cool",20,25,.95,-1,"Hits 2-5 times in one turn."])
    movedex.append([43,"Leer","Normal","Status","Cool",30,0,1,-1,"Lowers opponent's Defense."])
    movedex.append([44,"Bite","Dark","Physical","Tough",25,60,1,8,"May cause flinching."])
    movedex.append([45,"Growl","Normal","Status","Cute",40,0,1,-1,"Lowers opponent's Attack."])
    movedex.append([46,"Roar","Normal","Status","Cool",20,0,"—",-1,"In battles, the opponent switches. In the wild, the Pokémon runs."])
    movedex.append([47,"Sing","Normal","Status","Cute",15,0,0.55,-1,"Puts opponent to sleep."])
    movedex.append([48,"Supersonic","Normal","Status","Clever",20,0,0.55,-1,"Confuses opponent."])
    movedex.append([49,"Sonic Boom","Normal","Special","Cool",20,0,0.9,-1,"Always inflicts 20 HP."])
    movedex.append([50,"Disable","Normal","Status","Clever",20,0,1,-1,"Opponent can't use its last attack for a few turns."])
    movedex.append([51,"Acid","Poison","Special","Clever",30,40,1,-1,"May lower opponent's Special Defense."])
    movedex.append([52,"Ember","Fire","Special","Cute",25,40,1,-1,"May burn opponent."])
    movedex.append([53,"Flamethrower","Fire","Special","Beautiful",15,90,1,-1,"May burn opponent."])
    movedex.append([54,"Mist","Ice","Status","Beautiful",30,0,"—",-1,"User's stats cannot be changed for a period of time."])
    movedex.append([55,"Water Gun","Water","Special","Cute",25,40,1,0,"A damaging attack."])
    movedex.append([56,"Hydro Pump","Water","Special","Beautiful",5,110,0.8,0,"A damaging attack."])
    movedex.append([57,"Surf","Water","Special","Beautiful",15,90,1,-1,"Hits all adjacent Pokémon."])
    movedex.append([58,"Ice Beam","Ice","Special","Beautiful",10,90,1,-1,"May freeze opponent."])
    movedex.append([59,"Blizzard","Ice","Special","Beautiful",5,110,.7,-1,"May freeze opponent."])
    movedex.append([60,"Psybeam","Psychic","Special","Beautiful",20,65,1,-1,"May confuse opponent."])
    movedex.append([61,"Bubble Beam","Water","Special","Beautiful",20,65,1,-1,"May lower opponent's Speed."])
    movedex.append([62,"Aurora Beam","Ice","Special","Beautiful",20,65,1,-1,"May lower opponent's Attack."])
    movedex.append([63,"Hyper Beam","Normal","Special","Cool",5,150,0.9,-1,"User must recharge next turn."])
    movedex.append([64,"Peck","Flying","Physical","Cool",35,35,1,0,"A damaging attack."])
    movedex.append([65,"Drill Peck","Flying","Physical","Cool",20,80,1,0,"A damaging attack."])
    movedex.append([66,"Submission","Fighting","Physical","Cool",20,80,0.8,-1,"User receives recoil damage."])
    movedex.append([67,"Low Kick","Fighting","Physical","Tough",20,0,1,-1,"The heavier the opponent, the stronger the attack."])
    movedex.append([68,"Counter","Fighting","Physical","Tough",20,0,1,-1,"When hit by a Physical Attack, user strikes back with 2x power."])
    movedex.append([69,"Seismic Toss","Fighting","Physical","Tough",20,0,1,-1,"Inflicts damage equal to user's level."])
    movedex.append([70,"Strength","Normal","Physical","Tough",15,80,1,0,"A damaging attack."])
    movedex.append([71,"Absorb","Grass","Special","Clever",15,20,1,"","User recovers half the HP inflicted on opponent."])
    movedex.append([72,"Mega Drain","Grass","Special","Clever",15,40,1,-1,"User recovers half the HP inflicted on opponent."])
    movedex.append([73,"Leech Seed","Grass","Status","Clever",10,0,0.9,-1,"Drains HP from opponent each turn."])
    movedex.append([74,"Growth","Normal","Status","Beautiful",20,0,"—",-1,"Raises user's Attack and Special Attack."])
    movedex.append([75,"Razor Leaf","Grass","Physical","Cool",25,55,0.95,-1,"High critical hit ratio."])
    movedex.append([76,"Solar Beam","Grass","Special","Cool",10,200,1,-1,"Charges on first turn, attacks on second."])
    movedex.append([77,"Poison Powder","Poison","Status","Clever",35,0,0.75,-1,"Poisons opponent."])
    movedex.append([78,"Stun Spore","Grass","Status","Clever",30,0,0.75,-1,"Paralyzes opponent."])
    movedex.append([79,"Sleep Powder","Grass","Status","Clever",15,0,0.75,-1,"Puts opponent to sleep."])
    movedex.append([80,"Petal Dance","Grass","Special","Beautiful",10,120,1,4,"User attacks for 2-3 turns but then becomes confused."])
    movedex.append([81,"String Shot","Bug","Status","Clever",40,0,0.95,-1,"Sharply lowers opponent's Speed."])
    movedex.append([82,"Dragon Rage","Dragon","Special","Cool",10,0,1,-1,"Always inflicts 40 HP."])
    movedex.append([83,"Fire Spin","Fire","Special","Beautiful",15,35,.85,-1,"Traps opponent, damaging them for 4-5 turns."])
    movedex.append([84,"Thunder Shock","Electric","Special","Cool",30,40,1,-1,"May paralyze opponent."])
    movedex.append([85,"Thunderbolt","Electric","Special","Cool",15,90,1,-1,"May paralyze opponent."])
    movedex.append([86,"Thunder Wave","Electric","Status","Cool",20,0,.9,-1,"Paralyzes opponent."])
    movedex.append([87,"Thunder","Electric","Special","Cool",10,110,0.7,-1,"May paralyze opponent."])
    movedex.append([88,"Rock Throw","Rock","Physical","Tough",15,50,.9,0,"A damaging attack."])
    movedex.append([89,"Earthquake","Ground","Physical","Tough",10,100,1,0,"Power is doubled if opponent is underground from using Dig."])
    movedex.append([90,"Fissure","Ground","Physical","Tough",5,0,"~",-1,"One-Hit-KO, if it hits."])
    movedex.append([91,"Dig","Ground","Physical","Tough",10,80,1,-1,"Digs underground on first turn, attacks on second."])
    movedex.append([92,"Toxic","Poison","Status","Clever",10,0,.90,-1,"Badly poisons opponent."])
    movedex.append([93,"Confusion","Psychic","Special","Clever",25,50,1,-1,"May confuse opponent."])
    movedex.append([94,"Psychic","Psychic","Special","Clever",10,90,1,-1,"May lower opponent's Special Defense."])
    movedex.append([95,"Hypnosis","Psychic","Status","Clever",20,0,.6,-1,"Puts opponent to sleep."])
    movedex.append([96,"Meditate","Psychic","Status","Beautiful",40,0,"—",5,"Raises user's Attack."])
    movedex.append([97,"Agility","Psychic","Status","Cool",30,0,"—",-1,"Sharply raises user's Speed."])
    movedex.append([98,"Quick Attack","Normal","Physical","Cool",30,40,1,-1,"User attacks first."])
    movedex.append([99,"Rage","Normal","Physical","Tough",20,20,1,-1,"Raises user's Attack when hit."])
    movedex.append([100,"Teleport","Psychic","Status","Cool",20,0,"—",-1,"Always allows user to switch out."])
    movedex.append([101,"Night Shade","Ghost","Special","Clever",15,0,1,-1,"Inflicts damage equal to user's level."])
    movedex.append([102,"Mimic","Normal","Status","Cute",10,0,"-",-1,"Copies the opponent's last move."])
    movedex.append([103,"Screech","Normal","Status","Clever",40,0,0.85,-1,"Sharply lowers opponent's Defense."])
    movedex.append([104,"Double Team","Normal","Status","Cool",15,0,"—",-1,"Raises user's Evasiveness."])
    movedex.append([105,"Recover","Normal","Status","Clever",10,0,"—",-1,"User recovers half its max HP."])
    movedex.append([106,"Harden","Normal","Status","Tough",30,0,"—",-1,"Raises user's Defense."])
    movedex.append([107,"Minimize","Normal","Status","Cute",10,0,"—",-1,"Sharply raises user's Evasiveness."])
    movedex.append([108,"Smokescreen","Normal","Status","Clever",20,0,1,-1,"Lowers opponent's Accuracy."])
    movedex.append([109,"Confuse Ray","Ghost","Status","Clever",10,0,1,-1,"Confuses opponent."])
    movedex.append([110,"Withdraw","Water","Status","Cute",40,0,"—",-1,"Raises user's Defense."])
    movedex.append([111,"Defense Curl","Normal","Status","Cute",40,0,"—",-1,"Raises user's Defense."])
    movedex.append([112,"Barrier","Psychic","Status","Cool",20,0,"—",-1,"Sharply raises user's Defense."])
    movedex.append([113,"Light Screen","Psychic","Status","Beautiful",30,0,"—",-1,"Halves damage from Special attacks for 5 turns."])
    movedex.append([114,"Haze","Ice","Status","Beautiful",30,0,"-",-1,"Resets all stat changes."])
    movedex.append([115,"Reflect","Psychic","Status","Clever",20,0,"—",-1,"Halves damage from Physical attacks for 5 turns."])
    movedex.append([116,"Focus Energy","Normal","Status","Cool",30,0,"—",-1,"Increases critical hit ratio."])
    movedex.append([117,"Bide","Normal","Physical","Tough",10,0,"-",-1,"User takes damage for two turns then strikes back double."])
    movedex.append([118,"Metronome","Normal","Status","Cute",10,0,"—",-1,"User performs almost any move in the game at random."])
    movedex.append([119,"Mirror Move","Flying","Status","Clever",20,0,"—",-1,"User performs the opponent's last move."])
    movedex.append([120,"Self-Destruct","Normal","Physical","Beautiful",5,200,1,-1,"User faints."])
    movedex.append([121,"Egg Bomb","Normal","Physical","Cute",10,100,0.75,0,"A damaging attack."])
    movedex.append([122,"Lick","Ghost","Physical","Cute",30,30,1,-1,"May paralyze opponent."])
    movedex.append([123,"Smog","Poison","Special","Tough",20,30,0.7,-1,"May poison opponent."])
    movedex.append([124,"Sludge","Poison","Special","Tough",20,65,1,-1,"May poison opponent."])
    movedex.append([125,"Bone Club","Ground","Physical","Tough",20,65,0.85,-1,"May cause flinching."])
    movedex.append([126,"Fire Blast","Fire","Special","Beautiful",5,110,0.85,-1,"May burn opponent."])
    movedex.append([127,"Waterfall","Water","Physical","Tough",15,80,1,-1,"May cause flinching."])
    movedex.append([128,"Clamp","Water","Physical","Tough",15,35,.85,-1,"Traps opponent, damaging them for 4-5 turns."])
    movedex.append([129,"Swift","Normal","Special","Cool",20,60,"—",-1,"Ignores Accuracy and Evasiveness."])
    movedex.append([130,"Skull Bash","Normal","Physical","Tough",10,130,1,-1,"Raises Defense on first turn, attacks on second."])
    movedex.append([131,"Spike Cannon","Normal","Physical","Cool",15,20,1,-1,"Hits 2-5 times in one turn."])
    movedex.append([132,"Constrict","Normal","Physical","Tough",35,10,1,-1,"May lower opponent's Speed by one stage."])
    movedex.append([133,"Amnesia","Psychic","Status","Cute",20,0,"—",-1,"Sharply raises user's Special Defense."])
    movedex.append([134,"Kinesis","Psychic","Status","Clever",15,0,0.8,-1,"Lowers opponent's Accuracy."])
    movedex.append([135,"Soft-Boiled","Normal","Status","Cute",10,0,"—",-1,"User recovers half its max HP."])
    movedex.append([136,"High Jump Kick","Fighting","Physical","Cool",10,130,0.9,-1,"If it misses, the user loses half their HP."])
    movedex.append([137,"Glare","Normal","Status","Tough",30,0,1,-1,"Paralyzes opponent."])
    movedex.append([138,"Dream Eater","Psychic","Special","Clever",15,100,1,-1,"User recovers half the HP inflicted on a sleeping opponent."])
    movedex.append([139,"Poison Gas","Poison","Status","Clever",40,0,.90,-1,"Poisons opponent."])
    movedex.append([140,"Barrage","Normal","Physical","Cute",20,15,0.85,-1,"Hits 2-5 times in one turn."])
    movedex.append([141,"Leech Life","Bug","Physical","Clever",10,80,1,-1,"User recovers half the HP inflicted on opponent."])
    movedex.append([142,"Lovely Kiss","Normal","Status","Beautiful",10,0,0.75,-1,"Puts opponent to sleep."])
    movedex.append([143,"Sky Attack","Flying","Physical","Cool",5,200,0.9,-1,"Charges on first turn, attacks on second. May cause flinching."])
    movedex.append([144,"Transform","Normal","Status","Clever",10,0,"—",-1,"User takes on the form and attacks of the opponent."])
    movedex.append([145,"Bubble","Water","Special","Cute",30,40,1,-1,"May lower opponent's Speed."])
    movedex.append([146,"Dizzy Punch","Normal","Physical","Cute",10,70,1,-1,"May confuse opponent."])
    movedex.append([147,"Spore","Grass","Status","Beautiful",15,0,1,-1,"Puts opponent to sleep."])
    movedex.append([148,"Flash","Normal","Status","Beautiful",20,0,1,-1,"Lowers opponent's Accuracy."])
    movedex.append([149,"Psywave","Psychic","Special","Clever",15,0,1,-1,"Inflicts random damage unaffected by weakness or resistance."])
    movedex.append([150,"Splash","Normal","Status","Cute",40,0,"—","","Doesn't do ANYTHING."])
    movedex.append([151,"Acid Armor","Poison","Status","Tough",20,0,"—",-1,"Sharply raises user's Defense."])
    movedex.append([152,"Crabhammer","Water","Physical","Tough",10,100,.90,-1,"High critical hit ratio."])
    movedex.append([153,"Explosion","Normal","Physical","Beautiful",5,250,1,-1,"User faints."])
    movedex.append([154,"Fury Swipes","Normal","Physical","Tough",15,18,0.8,-1,"Hits 2-5 times in one turn."])
    movedex.append([155,"Bonemerang","Ground","Physical","Tough",10,50,0.9,-1,"Hits twice in one turn."])
    movedex.append([156,"Rest","Psychic","Status","Cute",10,0,"—",-1,"User sleeps for 2 turns, but user is fully healed."])
    movedex.append([157,"Rock Slide","Rock","Physical","Tough",10,75,0.9,-1,"May cause flinching."])
    movedex.append([158,"Hyper Fang","Normal","Physical","Cool",15,80,0.9,-1,"May cause flinching."])
    movedex.append([159,"Sharpen","Normal","Status","Cute",30,0,"—",-1,"Raises user's Attack."])
    movedex.append([160,"Conversion","Normal","Status","Beautiful",30,0,"—",-1,"Changes user's type to that of its first move."])
    movedex.append([161,"Tri Attack","Normal","Special","Beautiful",10,80,1,-1,"May paralyze, burn or freeze opponent."])
    movedex.append([162,"Super Fang","Normal","Physical","Tough",10,0,0.9,-1,"Always takes off half of the opponent's HP."])
    movedex.append([163,"Slash","Normal","Physical","Cool",20,70,1,-1,"High critical hit ratio."])
    movedex.append([164,"Substitute","Normal","Status","Cute",10,0,"—",-1,"Uses HP to creates a decoy that takes hits."])
    movedex.append([165,"Struggle","Normal","Physical","Tough",99,50,"—",-1,"Only usable when all PP are gone. Hurts the user."])
    movedex.append([166,"Sketch","Normal","Status","Clever",1,0,"—",-1,"Permanently copies the opponent's last move."])
    movedex.append([167,"Triple Kick","Fighting","Physical","Cool",10,10,0.9,-1,"Hits thrice in one turn at increasing power."])
    movedex.append([168,"Thief","Dark","Physical","Tough",25,60,1,-1,"Also steals opponent's held item."])
    movedex.append([169,"Spider Web","Bug","Status","Clever",10,0,"—",-1,"Opponent cannot escape/switch."])
    movedex.append([170,"Mind Reader","Normal","Status","Clever",5,0,"-",-1,"User's next attack is guaranteed to hit."])
    movedex.append([171,"Nightmare","Ghost","Status","Clever",15,0,1,-1,"The sleeping opponent loses 25% of its max HP each turn."])
    movedex.append([172,"Flame Wheel","Fire","Physical","Beautiful",25,60,1,-1,"May burn opponent."])
    movedex.append([173,"Snore","Normal","Special","Cute",15,50,1,-1,"Can only be used if asleep. May cause flinching."])
    movedex.append([174,"Curse","Ghost","Status","Tough",10,0,"—",-1,"Different effect for Ghosts."])
    movedex.append([175,"Flail","Normal","Physical","Cute",15,0,1,-1,"The lower the user's HP, the higher the power."])
    movedex.append([176,"Conversion 2","Normal","Status","Beautiful",30,0,"—",-1,"User changes type to become resistant to opponent's last move."])
    movedex.append([177,"Aeroblast","Flying","Special","Cool",5,100,0.95,-1,"High critical hit ratio."])
    movedex.append([178,"Cotton Spore","Grass","Status","Beautiful",40,0,1,-1,"Sharply lowers opponent's Speed."])
    movedex.append([179,"Reversal","Fighting","Physical","Cool",15,0,1,-1,"The lower the user's HP, the higher the power."])
    movedex.append([180,"Spite","Ghost","Status","Tough",10,0,1,-1,"The opponent's last move loses 2-5 PP."])
    movedex.append([181,"Powder Snow","Ice","Special","Beautiful",25,40,1,-1,"May freeze opponent."])
    movedex.append([182,"Protect","Normal","Status","Cute",10,0,"—",-1,"Protects the user, but may fail if used consecutively."])
    movedex.append([183,"Mach Punch","Fighting","Physical","Cool",30,40,1,-1,"User attacks first."])
    movedex.append([184,"Scary Face","Normal","Status","Tough",10,0,1,-1,"Sharply lowers opponent's Speed."])
    movedex.append([185,"Feint Attack","Dark","Physical","Clever",20,60,"—",-1,"Ignores Accuracy and Evasiveness."])
    movedex.append([186,"Sweet Kiss","Fairy","Status","Cute",10,0,0.75,-1,"Confuses opponent."])
    movedex.append([187,"Belly Drum","Normal","Status","Cute",10,0,"—",-1,"User loses 50% of its max HP, but Attack raises to maximum."])
    movedex.append([188,"Sludge Bomb","Poison","Special","Tough",10,90,1,-1,"May poison opponent."])
    movedex.append([189,"Mud-Slap","Ground","Special","Cute",10,20,1,-1,"Lowers opponent's Accuracy."])
    movedex.append([190,"Octazooka","Water","Special","Tough",10,65,0.85,-1,"May lower opponent's Accuracy."])
    movedex.append([191,"Spikes","Ground","Status","Clever",20,0,"—",-1,"Hurts opponents when they switch into battle."])
    movedex.append([192,"Zap Cannon","Electric","Special","Cool",5,120,0.5,-1,"Paralyzes opponent."])
    movedex.append([193,"Foresight","Normal","Status","Clever",40,0,"—",-1,"Resets opponent's Evasiveness, removes Ghost's immunities."])
    movedex.append([194,"Destiny Bond","Ghost","Status","Clever",5,0,"—",-1,"If the user faints, the opponent also faints."])
    movedex.append([195,"Perish Song","Normal","Status","Beautiful",5,0,"—",-1,"Any Pokémon in play when this attack is used faints in 3 turns."])
    movedex.append([196,"Icy Wind","Ice","Special","Beautiful",15,55,0.95,-1,"Lowers opponent's Speed."])
    movedex.append([197,"Detect","Fighting","Status","Cool",5,0,"—",-1,"Protects the user, but may fail if used consecutively."])
    movedex.append([198,"Bone Rush","Ground","Physical","Tough",10,25,.90,-1,"Hits 2-5 times in one turn."])
    movedex.append([199,"Lock-On","Normal","Status","Clever",5,0,"-",-1,"User's next attack is guaranteed to hit."])
    movedex.append([200,"Outrage","Dragon","Physical","Cool",10,120,1,4,"User attacks for 2-3 turns but then becomes confused."])
    movedex.append([201,"Sandstorm","Rock","Status","Tough",10,0,"—",-1,"Creates a sandstorm for 5 turns."])
    movedex.append([202,"Giga Drain","Grass","Special","Clever",10,75,1,-1,"User recovers half the HP inflicted on opponent."])
    movedex.append([203,"Endure","Normal","Status","Tough",10,0,"—",-1,"Always left with at least 1 HP, but may fail if used consecutively."])
    movedex.append([204,"Charm","Fairy","Status","Cute",20,0,1,-1,"Sharply lowers opponent's Attack."])
    movedex.append([205,"Rollout","Rock","Physical","Cute",20,30,0.9,-1,"Doubles in power each turn for 5 turns."])
    movedex.append([206,"False Swipe","Normal","Physical","Cool",40,40,1,-1,"Always leaves opponent with at least 1 HP."])
    movedex.append([207,"Swagger","Normal","Status","Cute",15,0,.85,-1,"Opponent becomes confused, but its Attack is sharply raised."])
    movedex.append([208,"Milk Drink","Normal","Status","Cute",10,0,"—",-1,"User recovers half its max HP."])
    movedex.append([209,"Spark","Electric","Physical","Cool",20,65,1,-1,"May paralyze opponent."])
    movedex.append([210,"Fury Cutter","Bug","Physical","Cool",20,40,0.95,-1,"Power increases each turn."])
    movedex.append([211,"Steel Wing","Steel","Physical","Cool",25,70,0.9,-1,"May raise user's Defense."])
    movedex.append([212,"Mean Look","Normal","Status","Beautiful",5,0,"—",-1,"Opponent cannot flee or switch."])
    movedex.append([213,"Attract","Normal","Status","Cute",15,0,1,-1,"If opponent is the opposite gender, it's less likely to attack."])
    movedex.append([214,"Sleep Talk","Normal","Status","Cute",10,0,"—",-1,"User performs one of its own moves while sleeping."])
    movedex.append([215,"Heal Bell","Normal","Status","Beautiful",5,0,"—",-1,"Heals the user's party's status conditions."])
    movedex.append([216,"Return","Normal","Physical","Cute",20,0,1,1,"Power increases with higher Friendship."])
    movedex.append([217,"Present","Normal","Physical","Cute",15,0,0.9,-1,"Either deals damage or heals."])
    movedex.append([218,"Frustration","Normal","Physical","Cute",20,0,1,-1,"Power decreases with higher Friendship."])
    movedex.append([219,"Safeguard","Normal","Status","Beautiful",25,0,"—",-1,"The user's party is protected from status conditions."])
    movedex.append([220,"Pain Split","Normal","Status","Clever",20,0,"-",-1,"The user's and opponent's HP becomes the average of both."])
    movedex.append([221,"Sacred Fire","Fire","Physical","Beautiful",5,100,0.95,-1,"May burn opponent."])
    movedex.append([222,"Magnitude","Ground","Physical","Tough",30,0,1,-1,"Hits with random power."])
    movedex.append([223,"Dynamic Punch","Fighting","Physical","Cool",5,100,0.5,-1,"Confuses opponent."])
    movedex.append([224,"Megahorn","Bug","Physical","Cool",10,120,0.85,0,"A damaging attack."])
    movedex.append([225,"Dragon Breath","Dragon","Special","Cool",20,60,1,-1,"May paralyze opponent."])
    movedex.append([226,"Baton Pass","Normal","Status","Cute",40,0,"—",-1,"User switches out and gives stat changes to the incoming Pokémon."])
    movedex.append([227,"Encore","Normal","Status","Cute",5,0,1,-1,"Forces opponent to keep using its last move for 3 turns."])
    movedex.append([228,"Pursuit","Dark","Physical","Clever",20,40,1,-1,"Double power if the opponent is switching out."])
    movedex.append([229,"Rapid Spin","Normal","Physical","Cool",40,50,1,-1,"Removes effects of trap moves, and boosts speed."])
    movedex.append([230,"Sweet Scent","Normal","Status","Cute",20,0,1,-1,"Lowers opponent's Evasiveness."])
    movedex.append([231,"Iron Tail","Steel","Physical","Cool",15,100,0.75,-1,"May lower opponent's Defense."])
    movedex.append([232,"Metal Claw","Steel","Physical","Cool",35,50,0.95,-1,"May raise user's Attack."])
    movedex.append([233,"Vital Throw","Fighting","Physical","Cool",10,70,"—",-1,"User attacks last, but ignores Accuracy and Evasiveness."])
    movedex.append([234,"Morning Sun","Normal","Status","Beautiful",5,0,"—",-1,"User recovers HP. Amount varies with the weather."])
    movedex.append([235,"Synthesis","Grass","Status","Clever",5,0,"—",-1,"User recovers HP. Amount varies with the weather."])
    movedex.append([236,"Moonlight","Fairy","Status","Beautiful",5,0,"—",-1,"User recovers HP. Amount varies with the weather."])
    movedex.append([237,"Hidden Power","Normal","Special","Clever",15,60,1,-1,"Type depends on user."])
    movedex.append([238,"Cross Chop","Fighting","Physical","Cool",5,100,0.8,-1,"High critical hit ratio."])
    movedex.append([239,"Twister","Dragon","Special","Cool",20,40,1,-1,"May cause flinching. Hits Pokémon using Fly/Bounce with double power."])
    movedex.append([240,"Rain Dance","Water","Status","Beautiful",5,0,"—",-1,"Makes it rain for 5 turns."])
    movedex.append([241,"Sunny Day","Fire","Status","Beautiful",5,0,"—",-1,"Makes it sunny for 5 turns."])
    movedex.append([242,"Crunch","Dark","Physical","Tough",15,80,1,-1,"May lower opponent's Defense."])
    movedex.append([243,"Mirror Coat","Psychic","Special","Beautiful",20,0,1,-1,"When hit by a Special Attack, user strikes back with 2x power."])
    movedex.append([244,"Psych Up","Normal","Status","Clever",10,0,"—",-1,"Copies the opponent's stat changes."])
    movedex.append([245,"Extreme Speed","Normal","Physical","Cool",5,80,1,-1,"User attacks first."])
    movedex.append([246,"Ancient Power","Rock","Special","Tough",5,60,1,-1,"May raise all user's stats at once."])
    movedex.append([247,"Shadow Ball","Ghost","Special","Clever",15,80,1,-1,"May lower opponent's Special Defense."])
    movedex.append([248,"Future Sight","Psychic","Special","Clever",10,120,1,-1,"Damage occurs 2 turns later."])
    movedex.append([249,"Rock Smash","Fighting","Physical","Tough",15,40,1,-1,"May lower opponent's Defense."])
    movedex.append([250,"Whirlpool","Water","Special","Beautiful",15,35,.85,-1,"Traps opponent, damaging them for 4-5 turns."])
    movedex.append([251,"Beat Up","Dark","Physical","Clever",10,0,1,-1,"Each Pokémon in your party attacks."])
    movedex.append([252,"Fake Out","Normal","Physical","Cute",10,40,1,-1,"User attacks first, foe flinches. Only usable on first turn."])
    movedex.append([253,"Uproar","Normal","Special","Cute",10,90,1,-1,"User attacks for 3 turns and prevents sleep."])
    movedex.append([254,"Stockpile","Normal","Status","Tough",20,0,"—",-1,"Stores energy for use with Spit Up and Swallow."])
    movedex.append([255,"Spit Up","Normal","Special","Tough",10,0,1,-1,"Power depends on how many times the user performed Stockpile."])
    movedex.append([256,"Swallow","Normal","Status","Tough",10,0,"—",-1,"The more times the user has performed Stockpile, the more HP is recovered."])
    movedex.append([257,"Heat Wave","Fire","Special","Beautiful",10,95,0.9,-1,"May burn opponent."])
    movedex.append([258,"Hail","Ice","Status","Beautiful",10,0,"—",-1,"Non-Ice types are damaged for 5 turns."])
    movedex.append([259,"Torment","Dark","Status","Tough",15,0,1,-1,"Opponent cannot use the same move in a row."])
    movedex.append([260,"Flatter","Dark","Status","Clever",15,0,1,-1,"Confuses opponent, but raises its Special Attack by two stages."])
    movedex.append([261,"Will-O-Wisp","Fire","Status","Beautiful",15,0,.85,-1,"Burns opponent."])
    movedex.append([262,"Memento","Dark","Status","Tough",10,0,1,-1,"User faints, sharply lowers opponent's Attack and Special Attack."])
    movedex.append([263,"Facade","Normal","Physical","Cute",20,70,1,-1,"Power doubles if user is burned, poisoned, or paralyzed."])
    movedex.append([264,"Focus Punch","Fighting","Physical","Tough",20,150,1,-1,"If the user is hit before attacking, it flinches instead."])
    movedex.append([265,"Smelling Salts","Normal","Physical","Tough",10,70,1,-1,"Power doubles if opponent is paralyzed, but cures it."])
    movedex.append([266,"Follow Me","Normal","Status","Cute",20,0,"—",-1,"In Multi Battles, the user takes all the attacks."])
    movedex.append([267,"Nature Power","Normal","Status","Beautiful",20,0,"—",-1,"Uses a certain move based on the current terrain."])
    movedex.append([268,"Charge","Electric","Status","Clever",20,0,"—",-1,"Raises user's Special Defense and next Electric move's power increases."])
    movedex.append([269,"Taunt","Dark","Status","Clever",20,0,1,-1,"Opponent can only use moves that attack."])
    movedex.append([270,"Helping Hand","Normal","Status","Clever",20,0,"—",-1,"In Multi Battles, boosts the power of the partner's move."])
    movedex.append([271,"Trick","Psychic","Status","Clever",10,0,1,-1,"Swaps held items with another Pokémon."])
    movedex.append([272,"Role Play","Psychic","Status","Cute",10,0,"—",-1,"User copies the opponent's Ability."])
    movedex.append([273,"Wish","Normal","Status","Cute",10,0,"—",-1,"The user recovers HP in the following turn."])
    movedex.append([274,"Assist","Normal","Status","Cute",20,0,"—",-1,"User performs a move known by its allies at random."])
    movedex.append([275,"Ingrain","Grass","Status","Clever",20,0,"—",-1,"User restores HP each turn. User cannot escape/switch."])
    movedex.append([276,"Superpower","Fighting","Physical","Tough",5,120,1,-1,"Lowers user's Attack and Defense."])
    movedex.append([277,"Magic Coat","Psychic","Status","Beautiful",15,0,"—",-1,"Reflects moves that cause status conditions back to the attacker."])
    movedex.append([278,"Recycle","Normal","Status","Clever",10,0,"—",-1,"User's used hold item is restored."])
    movedex.append([279,"Revenge","Fighting","Physical","Tough",10,60,1,-1,"Power increases if user was hit first."])
    movedex.append([280,"Brick Break","Fighting","Physical","Cool",15,75,1,-1,"Breaks through Reflect and Light Screen barriers."])
    movedex.append([281,"Yawn","Normal","Status","Cute",10,0,"—",-1,"Puts opponent to sleep in the next turn."])
    movedex.append([282,"Knock Off","Dark","Physical","Clever",20,65,1,-1,"Removes opponent's held item for the rest of the battle."])
    movedex.append([283,"Endeavor","Normal","Physical","Tough",5,0,1,-1,"Reduces opponent's HP to same as user's."])
    movedex.append([284,"Eruption","Fire","Special","Beautiful",5,150,1,-1,"Stronger when the user's HP is higher."])
    movedex.append([285,"Skill Swap","Psychic","Status","Clever",10,0,"—",-1,"The user swaps Abilities with the opponent."])
    movedex.append([286,"Imprison","Psychic","Status","Clever",10,0,"—",-1,"Opponent is unable to use moves that the user also knows."])
    movedex.append([287,"Refresh","Normal","Status","Cute",20,0,"—",-1,"Cures paralysis, poison, and burns."])
    movedex.append([288,"Grudge","Ghost","Status","Tough",5,0,"—",-1,"If the users faints after using this move, the PP for the opponent's last move is depleted."])
    movedex.append([289,"Snatch","Dark","Status","Clever",10,0,"—",-1,"Steals the effects of the opponent's next move."])
    movedex.append([290,"Secret Power","Normal","Physical","Clever",20,70,1,-1,"Effects of the attack vary with the location."])
    movedex.append([291,"Dive","Water","Physical","Beautiful",10,80,1,-1,"Dives underwater on first turn, attacks on second turn."])
    movedex.append([292,"Arm Thrust","Fighting","Physical","Tough",20,15,1,-1,"Hits 2-5 times in one turn."])
    movedex.append([293,"Camouflage","Normal","Status","Clever",20,0,"—",-1,"Changes user's type according to the location."])
    movedex.append([294,"Tail Glow","Bug","Status","Beautiful",20,0,"—",-1,"Drastically raises user's Special Attack."])
    movedex.append([295,"Luster Purge","Psychic","Special","Clever",5,70,1,-1,"May lower opponent's Special Defense."])
    movedex.append([296,"Mist Ball","Psychic","Special","Clever",5,70,1,-1,"May lower opponent's Special Attack."])
    movedex.append([297,"Feather Dance","Flying","Status","Beautiful",15,0,1,-1,"Sharply lowers opponent's Attack."])
    movedex.append([298,"Teeter Dance","Normal","Status","Cute",20,0,1,-1,"Confuses all Pokémon."])
    movedex.append([299,"Blaze Kick","Fire","Physical","Cool",10,85,0.9,-1,"High critical hit ratio. May burn opponent."])
    movedex.append([300,"Mud Sport","Ground","Status","Cute",15,0,"—",-1,"Weakens the power of Electric-type moves."])
    movedex.append([301,"Ice Ball","Ice","Physical","Beautiful",20,30,0.9,-1,"Doubles in power each turn for 5 turns."])
    movedex.append([302,"Needle Arm","Grass","Physical","Clever",15,60,1,-1,"May cause flinching."])
    movedex.append([303,"Slack Off","Normal","Status","Cute",10,0,"—",-1,"User recovers half its max HP."])
    movedex.append([304,"Hyper Voice","Normal","Special","Cool",10,90,1,0,"A damaging attack."])
    movedex.append([305,"Poison Fang","Poison","Physical","Clever",15,50,1,-1,"May badly poison opponent."])
    movedex.append([306,"Crush Claw","Normal","Physical","Cool",10,75,0.95,-1,"May lower opponent's Defense."])
    movedex.append([307,"Blast Burn","Fire","Special","Beautiful",5,150,0.9,-1,"User must recharge next turn."])
    movedex.append([308,"Hydro Cannon","Water","Special","Beautiful",5,150,0.9,-1,"User must recharge next turn."])
    movedex.append([309,"Meteor Mash","Steel","Physical","Cool",10,90,.90,-1,"May raise user's Attack."])
    movedex.append([310,"Astonish","Ghost","Physical","Cute",15,30,1,-1,"May cause flinching."])
    movedex.append([311,"Weather Ball","Normal","Special","Beautiful",10,50,1,-1,"Move's power and type changes with the weather."])
    movedex.append([312,"Aromatherapy","Grass","Status","Clever",5,0,"—",-1,"Cures all status problems in your party."])
    movedex.append([313,"Fake Tears","Dark","Status","Cute",20,0,1,-1,"Sharply lowers opponent's Special Defense."])
    movedex.append([314,"Air Cutter","Flying","Special","Cool",25,60,0.95,-1,"High critical hit ratio."])
    movedex.append([315,"Overheat","Fire","Special","Beautiful",5,130,0.9,-1,"Sharply lowers user's Special Attack."])
    movedex.append([316,"Odor Sleuth","Normal","Status","Clever",40,0,"—",-1,"Resets opponent's Evasiveness, removes Ghost's immunities."])
    movedex.append([317,"Rock Tomb","Rock","Physical","Clever",15,60,.95,6,"Lowers opponent's Speed."])
    movedex.append([318,"Silver Wind","Bug","Special","Beautiful",5,60,1,-1,"May raise all stats of user at once."])
    movedex.append([319,"Metal Sound","Steel","Status","Clever",40,0,0.85,-1,"Sharply lowers opponent's Special Defense."])
    movedex.append([320,"Grass Whistle","Grass","Status","Clever",15,0,0.55,-1,"Puts opponent to sleep."])
    movedex.append([321,"Tickle","Normal","Status","Cute",20,0,1,-1,"Lowers opponent's Attack and Defense."])
    movedex.append([322,"Cosmic Power","Psychic","Status","Beautiful",20,0,"—",-1,"Raises user's Defense and Special Defense."])
    movedex.append([323,"Water Spout","Water","Special","Beautiful",5,150,1,-1,"The higher the user's HP, the higher the damage caused."])
    movedex.append([324,"Signal Beam","Bug","Special","Beautiful",15,75,1,-1,"May confuse opponent."])
    movedex.append([325,"Shadow Punch","Ghost","Physical","Clever",20,60,"—",-1,"Ignores Accuracy and Evasiveness."])
    movedex.append([326,"Extrasensory","Psychic","Special","Cool",20,80,1,-1,"May cause flinching."])
    movedex.append([327,"Sky Uppercut","Fighting","Physical","Cool",15,85,0.9,-1,"Hits the opponent, even during Fly."])
    movedex.append([328,"Sand Tomb","Ground","Physical","Clever",15,35,.85,-1,"Traps opponent, damaging them for 4-5 turns."])
    movedex.append([329,"Sheer Cold","Ice","Special","Beautiful",5,0,"~",-1,"One-Hit-KO, if it hits."])
    movedex.append([330,"Muddy Water","Water","Special","Tough",10,90,0.85,-1,"May lower opponent's Accuracy."])
    movedex.append([331,"Bullet Seed","Grass","Physical","Cool",30,25,1,-1,"Hits 2-5 times in one turn."])
    movedex.append([332,"Aerial Ace","Flying","Physical","Cool",20,60,"—",-1,"Ignores Accuracy and Evasiveness."])
    movedex.append([333,"Icicle Spear","Ice","Physical","Beautiful",30,25,1,-1,"Hits 2-5 times in one turn."])
    movedex.append([334,"Iron Defense","Steel","Status","Tough",15,0,"—",-1,"Sharply raises user's Defense."])
    movedex.append([335,"Block","Normal","Status","Cute",5,0,"—",-1,"Opponent cannot flee or switch."])
    movedex.append([336,"Howl","Normal","Status","Cool",40,0,"—",5,"Raises user's Attack."])
    movedex.append([337,"Dragon Claw","Dragon","Physical","Cool",15,80,1,0,"A damaging attack."])
    movedex.append([338,"Frenzy Plant","Grass","Special","Cool",5,150,0.9,-1,"User must recharge next turn."])
    movedex.append([339,"Bulk Up","Fighting","Status","Cool",20,0,"—",-1,"Raises user's Attack and Defense."])
    movedex.append([340,"Bounce","Flying","Physical","Cute",5,85,0.85,-1,"Springs up on first turn, attacks on second. May paralyze opponent."])
    movedex.append([341,"Mud Shot","Ground","Special","Tough",15,55,0.95,-1,"Lowers opponent's Speed."])
    movedex.append([342,"Poison Tail","Poison","Physical","Clever",25,50,1,-1,"High critical hit ratio. May poison opponent."])
    movedex.append([343,"Covet","Normal","Physical","Cute",25,60,1,-1,"Opponent's item is stolen by the user."])
    movedex.append([344,"Volt Tackle","Electric","Physical","Cool",15,120,1,-1,"User receives recoil damage. May paralyze opponent."])
    movedex.append([345,"Magical Leaf","Grass","Special","Beautiful",20,60,"—",-1,"Ignores Accuracy and Evasiveness."])
    movedex.append([346,"Water Sport","Water","Status","Cute",15,0,"—",-1,"Weakens the power of Fire-type moves."])
    movedex.append([347,"Calm Mind","Psychic","Status","Clever",20,0,"—",-1,"Raises user's Special Attack and Special Defense."])
    movedex.append([348,"Leaf Blade","Grass","Physical","Cool",15,90,1,-1,"High critical hit ratio."])
    movedex.append([349,"Dragon Dance","Dragon","Status","Cool",20,0,"—",3,"Raises user's Attack and Speed."])
    movedex.append([350,"Rock Blast","Rock","Physical","Tough",10,25,.90,-1,"Hits 2-5 times in one turn."])
    movedex.append([351,"Shock Wave","Electric","Special","Cool",20,60,"—",-1,"Ignores Accuracy and Evasiveness."])
    movedex.append([352,"Water Pulse","Water","Special","Beautiful",20,60,1,-1,"May confuse opponent."])
    movedex.append([353,"Doom Desire","Steel","Special","Beautiful",5,140,1,-1,"Damage occurs 2 turns later."])
    movedex.append([354,"Psycho Boost","Psychic","Special","Clever",5,140,0.9,-1,"Sharply lowers user's Special Attack."])
    movedex.append([355,"Roost","Flying","Status","Clever",10,0,"—",2,"User recovers half of its max HP and loses the Flying type temporarily."])
    movedex.append([356,"Gravity","Psychic","Status","Clever",5,0,"—",-1,"Prevents moves like Fly and Bounce and the Ability Levitate for 5 turns."])
    movedex.append([357,"Miracle Eye","Psychic","Status","Clever",40,0,"—",-1,"Resets opponent's Evasiveness, removes Dark's Psychic immunity."])
    movedex.append([358,"Wake-Up Slap","Fighting","Physical","Tough",10,70,1,-1,"Power doubles if opponent is asleep, but wakes it up."])
    movedex.append([359,"Hammer Arm","Fighting","Physical","Tough",10,100,0.9,-1,"Lowers user's Speed."])
    movedex.append([360,"Gyro Ball","Steel","Physical","Cool",5,0,1,-1,"The slower the user, the stronger the attack."])
    movedex.append([361,"Healing Wish","Psychic","Status","Beautiful",10,0,"—",-1,"The user faints and the next Pokémon released is fully healed."])
    movedex.append([362,"Brine","Water","Special","Tough",10,65,1,-1,"Power doubles if opponent's HP is less than 50%."])
    movedex.append([363,"Natural Gift","Normal","Physical","Clever",15,0,1,-1,"Power and type depend on the user's held berry."])
    movedex.append([364,"Feint","Normal","Physical","Clever",10,30,1,-1,"Breaks through protecting moves."])
    movedex.append([365,"Pluck","Flying","Physical","Cute",20,60,1,-1,"If the opponent is holding a berry, its effect is stolen by user."])
    movedex.append([366,"Tailwind","Flying","Status","Cool",15,0,"—",-1,"Doubles Speed for 4 turns."])
    movedex.append([367,"Acupressure","Normal","Status","Tough",30,0,"—",-1,"Sharply raises a random stat."])
    movedex.append([368,"Metal Burst","Steel","Physical","Cool",10,0,1,-1,"Deals damage equal to 1.5x opponent's attack."])
    movedex.append([369,"U-turn","Bug","Physical","Cute",20,70,1,-1,"User switches out immediately after attacking."])
    movedex.append([370,"Close Combat","Fighting","Physical","Tough",5,120,1,-1,"Lowers user's Defense and Special Defense."])
    movedex.append([371,"Payback","Dark","Physical","Tough",10,50,1,-1,"Power doubles if the user was attacked first."])
    movedex.append([372,"Assurance","Dark","Physical","Clever",10,60,1,-1,"Power doubles if opponent already took damage in the same turn."])
    movedex.append([373,"Embargo","Dark","Status","Clever",15,0,1,-1,"Opponent cannot use items."])
    # Discard: Replaces Fling
    movedex.append([374,"Discard","Dark","Status","Clever",10,0,1,-1,"Toss away your item to raise speed and evasion sharply. (Replaces Fling)"])
    movedex.append([375,"Psycho Shift","Psychic","Status","Clever",10,0,1,-1,"Gives the opponent the user's status condition, if it hits."])
    movedex.append([376,"Trump Card","Normal","Special","Cool",5,0,"—",-1,"The lower the PP, the higher the power."])
    movedex.append([377,"Heal Block","Psychic","Status","Clever",15,0,1,-1,"Prevents the opponent from restoring HP for 5 turns."])
    movedex.append([378,"Wring Out","Normal","Special","Tough",5,0,1,-1,"The higher the opponent's HP, the higher the damage."])
    movedex.append([379,"Power Trick","Psychic","Status","Clever",10,0,"—",-1,"User's own Attack and Defense switch."])
    movedex.append([380,"Gastro Acid","Poison","Status","Tough",10,0,1,-1,"Cancels out the effect of the opponent's Ability."])
    movedex.append([381,"Lucky Chant","Normal","Status","Cute",30,0,"—",-1,"Opponent cannot land critical hits for 5 turns."])
    movedex.append([382,"Me First","Normal","Status","Clever",20,0,"—",-1,"User copies the opponent's attack with 1.5× power."])
    movedex.append([383,"Copycat","Normal","Status","Cute",20,0,"—",-1,"Copies the last successful move."])
    movedex.append([384,"Power Swap","Psychic","Status","Clever",10,0,"—",-1,"User and opponent swap Attack and Special Attack."])
    movedex.append([385,"Guard Swap","Psychic","Status","Clever",10,0,"—",-1,"User and opponent swap Defense and Special Defense."])
    movedex.append([386,"Punishment","Dark","Physical","Cool",5,0,1,-1,"Power increases when opponent's stats have been raised."])
    movedex.append([387,"Last Resort","Normal","Physical","Cute",5,140,1,-1,"Can only be used after all other moves are used."])
    movedex.append([388,"Worry Seed","Grass","Status","Clever",10,0,1,-1,"Changes the opponent's Ability to Insomnia."])
    movedex.append([389,"Sucker Punch","Dark","Physical","Clever",5,70,1,-1,"User attacks first, but only works if opponent is readying an attack."])
    movedex.append([390,"Toxic Spikes","Poison","Status","Clever",20,0,"—",-1,"Poisons opponents when they switch into battle."])
    movedex.append([391,"Heart Swap","Psychic","Status","Clever",10,0,"—",-1,"Stat changes are swapped with the opponent."])
    movedex.append([392,"Aqua Ring","Water","Status","Beautiful",20,0,"—",-1,"Restores a little HP each turn."])
    movedex.append([393,"Magnet Rise","Electric","Status","Clever",10,0,"—",-1,"User becomes immune to Ground-type moves for 5 turns."])
    movedex.append([394,"Flare Blitz","Fire","Physical","Cool",15,120,1,-1,"User receives recoil damage. May burn opponent."])
    movedex.append([395,"Force Palm","Fighting","Physical","Cool",10,60,1,-1,"May paralyze opponent."])
    movedex.append([396,"Aura Sphere","Fighting","Special","Beautiful",20,80,"—",-1,"Ignores Accuracy and Evasiveness."])
    movedex.append([397,"Rock Polish","Rock","Status","Tough",20,0,"—",-1,"Sharply raises user's Speed."])
    movedex.append([398,"Poison Jab","Poison","Physical","Tough",20,80,1,-1,"May poison the opponent."])
    movedex.append([399,"Dark Pulse","Dark","Special","Cool",15,80,1,-1,"May cause flinching."])
    movedex.append([400,"Night Slash","Dark","Physical","Cool",15,70,1,-1,"High critical hit ratio."])
    movedex.append([401,"Aqua Tail","Water","Physical","Beautiful",10,90,0.9,0,"A damaging attack."])
    movedex.append([402,"Seed Bomb","Grass","Physical","Tough",15,80,1,0,"A damaging attack."])
    movedex.append([403,"Air Slash","Flying","Special","Cool",15,75,0.95,-1,"May cause flinching."])
    movedex.append([404,"X-Scissor","Bug","Physical","Cool",15,80,1,0,"A damaging attack."])
    movedex.append([405,"Bug Buzz","Bug","Special","Beautiful",10,90,1,-1,"May lower opponent's Special Defense."])
    movedex.append([406,"Dragon Pulse","Dragon","Special","Beautiful",10,85,1,0,"A damaging attack."])
    movedex.append([407,"Dragon Rush","Dragon","Physical","Tough",10,100,0.75,-1,"May cause flinching."])
    movedex.append([408,"Power Gem","Rock","Special","Beautiful",20,80,1,0,"A damaging attack."])
    movedex.append([409,"Drain Punch","Fighting","Physical","Tough",10,75,1,-1,"User recovers half the HP inflicted on opponent."])
    movedex.append([410,"Vacuum Wave","Fighting","Special","Cool",30,40,1,-1,"User attacks first."])
    movedex.append([411,"Focus Blast","Fighting","Special","Cool",5,120,0.7,-1,"May lower opponent's Special Defense."])
    movedex.append([412,"Energy Ball","Grass","Special","Beautiful",10,90,1,-1,"May lower opponent's Special Defense."])
    movedex.append([413,"Brave Bird","Flying","Physical","Cool",15,120,1,-1,"User receives recoil damage."])
    movedex.append([414,"Earth Power","Ground","Special","Beautiful",10,90,1,-1,"May lower opponent's Special Defense."])
    movedex.append([415,"Switcheroo","Dark","Status","Clever",10,0,1,-1,"Swaps held items with another Pokémon."])
    movedex.append([416,"Giga Impact","Normal","Physical","Tough",5,150,0.9,-1,"User must recharge next turn."])
    movedex.append([417,"Nasty Plot","Dark","Status","Clever",20,0,"—",-1,"Sharply raises user's Special Attack."])
    movedex.append([418,"Bullet Punch","Steel","Physical","Tough",30,40,1,-1,"User attacks first."])
    movedex.append([419,"Avalanche","Ice","Physical","Beautiful",10,60,1,-1,"Power doubles if user took damage first."])
    movedex.append([420,"Ice Shard","Ice","Physical","Beautiful",30,40,1,-1,"User attacks first."])
    movedex.append([421,"Shadow Claw","Ghost","Physical","Cool",15,70,1,-1,"High critical hit ratio."])
    movedex.append([422,"Thunder Fang","Electric","Physical","Cool",15,65,0.95,-1,"May cause flinching and/or paralyze opponent."])
    movedex.append([423,"Ice Fang","Ice","Physical","Cool",15,65,0.95,-1,"May cause flinching and/or freeze opponent."])
    movedex.append([424,"Fire Fang","Fire","Physical","Cool",15,65,0.95,-1,"May cause flinching and/or burn opponent."])
    movedex.append([425,"Shadow Sneak","Ghost","Physical","Clever",30,40,1,-1,"User attacks first."])
    movedex.append([426,"Mud Bomb","Ground","Special","Cute",10,65,0.85,-1,"May lower opponent's Accuracy."])
    movedex.append([427,"Psycho Cut","Psychic","Physical","Cool",20,70,1,-1,"High critical hit ratio."])
    movedex.append([428,"Zen Headbutt","Psychic","Physical","Clever",15,80,0.9,-1,"May cause flinching."])
    movedex.append([429,"Mirror Shot","Steel","Special","Beautiful",10,65,0.85,-1,"May lower opponent's Accuracy."])
    movedex.append([430,"Flash Cannon","Steel","Special","Beautiful",10,80,1,-1,"May lower opponent's Special Defense."])
    movedex.append([431,"Rock Climb","Normal","Physical","Tough",20,90,0.85,-1,"May confuse opponent."])
    movedex.append([432,"Defog","Flying","Status","Cool",15,0,"—",-1,"Lowers opponent's Evasiveness and clears fog."])
    movedex.append([433,"Trick Room","Psychic","Status","Clever",5,0,"—",-1,"Slower Pokémon move first in the turn for 5 turns."])
    movedex.append([434,"Draco Meteor","Dragon","Special","Beautiful",5,130,0.9,-1,"Sharply lowers user's Special Attack."])
    movedex.append([435,"Discharge","Electric","Special","Beautiful",15,80,1,-1,"May paralyze opponent."])
    movedex.append([436,"Lava Plume","Fire","Special","Tough",15,80,1,-1,"May burn opponent."])
    movedex.append([437,"Leaf Storm","Grass","Special","Beautiful",5,130,0.9,-1,"Sharply lowers user's Special Attack."])
    movedex.append([438,"Power Whip","Grass","Physical","Tough",10,120,0.85,0,"A damaging attack."])
    movedex.append([439,"Rock Wrecker","Rock","Physical","Tough",5,150,0.9,-1,"User must recharge next turn."])
    movedex.append([440,"Cross Poison","Poison","Physical","Cool",20,70,1,-1,"High critical hit ratio. May poison opponent."])
    movedex.append([441,"Gunk Shot","Poison","Physical","Tough",5,120,.80,-1,"May poison opponent."])
    movedex.append([442,"Iron Head","Steel","Physical","Tough",15,80,1,-1,"May cause flinching."])
    movedex.append([443,"Magnet Bomb","Steel","Physical","Cool",20,60,"—",-1,"Ignores Accuracy and Evasiveness."])
    movedex.append([444,"Stone Edge","Rock","Physical","Tough",5,100,0.8,-1,"High critical hit ratio."])
    movedex.append([445,"Captivate","Normal","Status","Cute",20,0,1,-1,"Sharply lowers opponent's Special Attack if opposite gender."])
    movedex.append([446,"Stealth Rock","Rock","Status","Cool",20,0,"—",-1,"Damages opponent switching into battle."])
    movedex.append([447,"Grass Knot","Grass","Special","Cute",20,0,1,-1,"The heavier the opponent, the stronger the attack."])
    movedex.append([448,"Chatter","Flying","Special","Cute",20,65,1,-1,"Confuses opponent."])
    movedex.append([449,"Judgment","Normal","Special","Beautiful",10,100,1,-1,"Type depends on the Arceus Plate being held."])
    movedex.append([450,"Bug Bite","Bug","Physical","Cute",20,60,1,-1,"Receives the effect from the opponent's held berry."])
    movedex.append([451,"Charge Beam","Electric","Special","Beautiful",10,50,0.9,-1,"May raise user's Special Attack."])
    movedex.append([452,"Wood Hammer","Grass","Physical","Tough",15,120,1,-1,"User receives recoil damage."])
    movedex.append([453,"Aqua Jet","Water","Physical","Cool",20,40,1,-1,"User attacks first."])
    movedex.append([454,"Attack Order","Bug","Physical","Clever",15,90,1,-1,"High critical hit ratio."])
    movedex.append([455,"Defend Order","Bug","Status","Clever",10,0,"—",-1,"Raises user's Defense and Special Defense."])
    movedex.append([456,"Heal Order","Bug","Status","Clever",10,0,"—",-1,"User recovers half its max HP."])
    movedex.append([457,"Head Smash","Rock","Physical","Tough",5,150,0.8,-1,"User receives recoil damage."])
    movedex.append([458,"Double Hit","Normal","Physical","Cool",10,35,0.9,-1,"Hits twice in one turn."])
    movedex.append([459,"Roar of Time","Dragon","Special","Beautiful",5,150,0.9,-1,"User must recharge next turn."])
    movedex.append([460,"Spacial Rend","Dragon","Special","Beautiful",5,100,0.95,-1,"High critical hit ratio."])
    movedex.append([461,"Lunar Dance","Psychic","Status","Beautiful",10,0,"—",-1,"The user faints but the next Pokémon released is fully healed."])
    movedex.append([462,"Crush Grip","Normal","Physical","Tough",5,0,1,-1,"More powerful when opponent has higher HP."])
    movedex.append([463,"Magma Storm","Fire","Special","Tough",5,100,.75,-1,"Traps opponent, damaging them for 4-5 turns."])
    movedex.append([464,"Dark Void","Dark","Status","Clever",10,0,.50,-1,"Puts all adjacent opponents to sleep."])
    movedex.append([465,"Seed Flare","Grass","Special","Beautiful",5,120,0.85,-1,"May lower opponent's Special Defense."])
    movedex.append([466,"Ominous Wind","Ghost","Special","Beautiful",5,60,1,-1,"May raise all user's stats at once."])
    movedex.append([467,"Shadow Force","Ghost","Physical","Cool",5,120,1,-1,"Disappears on first turn, attacks on second. Can strike through Protect/Detect."])
    movedex.append([468,"Hone Claws","Dark","Status","Cute",15,0,"—",-1,"Raises user's Attack and Accuracy."])
    movedex.append([469,"Wide Guard","Rock","Status","Tough",10,0,"—",-1,"Protects the user's team from multi-target attacks."])
    movedex.append([470,"Guard Split","Psychic","Status","Clever",10,0,"—",-1,"Averages Defense and Special Defense with the target."])
    movedex.append([471,"Power Split","Psychic","Status","Clever",10,0,"—",-1,"Averages Attack and Special Attack with the target."])
    movedex.append([472,"Wonder Room","Psychic","Status","Clever",10,0,"—",-1,"Swaps every Pokémon's Defense and Special Defense for 5 turns."])
    movedex.append([473,"Psyshock","Psychic","Special","Beautiful",10,80,1,-1,"Inflicts damage based on the target's Defense, not Special Defense."])
    movedex.append([474,"Venoshock","Poison","Special","Beautiful",10,65,1,-1,"Inflicts double damage if the target is poisoned."])
    movedex.append([475,"Autotomize","Steel","Status","Beautiful",15,0,"—",-1,"Reduces weight and sharply raises Speed."])
    movedex.append([476,"Rage Powder","Bug","Status","Clever",20,0,"—",-1,"Forces attacks to hit user, not team-mates."])
    movedex.append([477,"Telekinesis","Psychic","Status","Clever",15,0,"—",-1,"Ignores opponent's Evasiveness for three turns, add Ground immunity."])
    movedex.append([478,"Magic Room","Psychic","Status","Clever",10,0,"—",-1,"Suppresses the effects of held items for five turns."])
    movedex.append([479,"Smack Down","Rock","Physical","Tough",15,50,1,-1,"Makes Flying-type Pokémon vulnerable to Ground moves."])
    movedex.append([480,"Storm Throw","Fighting","Physical","Cool",10,60,1,-1,"Always results in a critical hit."])
    movedex.append([481,"Flame Burst","Fire","Special","Beautiful",15,70,1,-1,"May also injure nearby Pokémon."])
    movedex.append([482,"Sludge Wave","Poison","Special","Tough",10,95,1,-1,"May poison opponent."])
    movedex.append([483,"Quiver Dance","Bug","Status","Beautiful",20,0,"-",-1,"Raises user's Special Attack, Special Defense and Speed."])
    movedex.append([484,"Heavy Slam","Steel","Physical","Tough",10,0,1,-1,"The heavier the user, the stronger the attack."])
    movedex.append([485,"Synchronoise","Psychic","Special","Clever",10,120,1,-1,"Hits any Pokémon that shares a type with the user."])
    movedex.append([486,"Electro Ball","Electric","Special","Cool",10,0,1,-1,"The faster the user, the stronger the attack."])
    movedex.append([487,"Soak","Water","Status","Cute",20,0,1,-1,"Changes the target's type to water."])
    movedex.append([488,"Flame Charge","Fire","Physical","Cool",20,50,1,-1,"Raises user's Speed."])
    movedex.append([489,"Coil","Poison","Status","Tough",20,0,"—",-1,"Raises user's Attack, Defense and Accuracy."])
    movedex.append([490,"Low Sweep","Fighting","Physical","Clever",20,65,1,-1,"Lowers opponent's Speed."])
    movedex.append([491,"Acid Spray","Poison","Special","Beautiful",20,40,1,-1,"Sharply lowers opponent's Special Defense."])
    movedex.append([492,"Foul Play","Dark","Physical","Clever",15,95,1,-1,"Uses the opponent's Attack stat."])
    movedex.append([493,"Simple Beam","Normal","Status","Cute",15,0,1,-1,"Changes target's ability to Simple."])
    movedex.append([494,"Entrainment","Normal","Status","Cute",15,0,1,-1,"Makes target's ability same as user's."])
    movedex.append([495,"After You","Normal","Status","Cute",15,0,"—",-1,"Gives target priority in the next turn."])
    movedex.append([496,"Round","Normal","Special","Beautiful",15,60,1,-1,"Power increases if teammates use it in the same turn."])
    movedex.append([497,"Echoed Voice","Normal","Special","Beautiful",15,40,1,-1,"Power increases each turn."])
    movedex.append([498,"Chip Away","Normal","Physical","Tough",20,70,1,-1,"Ignores opponent's stat changes."])
    movedex.append([499,"Clear Smog","Poison","Special","Beautiful",15,50,"—",-1,"Removes all of the target's stat changes."])
    movedex.append([500,"Stored Power","Psychic","Special","Clever",10,20,1,-1,"Power increases when user's stats have been raised."])
    movedex.append([501,"Quick Guard","Fighting","Status","Cool",15,0,"—",-1,"Protects the user's team from high-priority moves."])
    movedex.append([502,"Ally Switch","Psychic","Status","Clever",15,0,"—",-1,"User switches with opposite teammate."])
    movedex.append([503,"Scald","Water","Special","Tough",15,80,1,-1,"May burn opponent."])
    movedex.append([504,"Shell Smash","Normal","Status","Tough",15,0,"—",-1,"Sharply raises user's Attack, Special Attack and Speed but lowers Defense and Special Defense."])
    movedex.append([505,"Heal Pulse","Psychic","Status","Beautiful",10,0,"—",-1,"Restores half the target's max HP."])
    movedex.append([506,"Hex","Ghost","Special","Clever",10,65,1,-1,"Inflicts more damage if the target has a status condition."])
    movedex.append([507,"Sky Drop","Flying","Physical","Tough",10,60,1,-1,"Takes opponent into the air on first turn, drops them on second turn."])
    movedex.append([508,"Shift Gear","Steel","Status","Clever",10,0,"—",-1,"Raises user's Attack and sharply raises Speed."])
    movedex.append([509,"Circle Throw","Fighting","Physical","Cool",10,60,0.9,-1,"In battles, the opponent switches. In the wild, the Pokémon runs."])
    movedex.append([510,"Incinerate","Fire","Special","Tough",15,60,1,-1,"Destroys the target's held berry."])
    movedex.append([511,"Quash","Dark","Status","Clever",15,0,1,-1,"Makes the target act last this turn."])
    movedex.append([512,"Acrobatics","Flying","Physical","Cool",15,55,1,-1,"Stronger when the user does not have a held item."])
    movedex.append([513,"Reflect Type","Normal","Status","Clever",15,0,"—",-1,"User becomes the target's type."])
    movedex.append([514,"Retaliate","Normal","Physical","Cool",5,70,1,-1,"Inflicts double damage if a teammate fainted on the last turn."])
    movedex.append([515,"Final Gambit","Fighting","Special","Tough",5,0,1,-1,"Inflicts damage equal to the user's remaining HP. User faints."])
    movedex.append([516,"Bestow","Normal","Status","Cute",15,0,"—",-1,"Gives the user's held item to the target."])
    movedex.append([517,"Inferno","Fire","Special","Beautiful",5,100,0.5,-1,"Burns opponent."])
    movedex.append([518,"Water Pledge","Water","Special","Beautiful",10,80,1,-1,"Added effects appear if preceded by Fire Pledge or succeeded by Grass Pledge."])
    movedex.append([519,"Fire Pledge","Fire","Special","Beautiful",10,80,1,-1,"Added effects appear if combined with Grass Pledge or Water Pledge."])
    movedex.append([520,"Grass Pledge","Grass","Special","Beautiful",10,80,1,-1,"Added effects appear if preceded by Water Pledge or succeeded by Fire Pledge."])
    movedex.append([521,"Volt Switch","Electric","Special","Cool",20,70,1,-1,"User must switch out after attacking."])
    movedex.append([522,"Struggle Bug","Bug","Special","Cute",20, 50,1,-1,"Lowers opponent's Special Attack."])
    movedex.append([523,"Bulldoze","Ground","Physical","Tough",20,60,1,-1,"Lowers opponent's Speed."])
    movedex.append([524,"Frost Breath","Ice","Special","Beautiful",10,60,0.9,-1,"Always results in a critical hit."])
    movedex.append([525,"Dragon Tail","Dragon","Physical","Tough",10,60,0.9,-1,"In battles, the opponent switches. In the wild, the Pokémon runs."])
    movedex.append([526,"Work Up","Normal","Status","Tough",30,0,"—",-1,"Raises user's Attack and Special Attack."])
    movedex.append([527,"Electroweb","Electric","Special","Beautiful",15,55,0.95,-1,"Lowers opponent's Speed."])
    movedex.append([528,"Wild Charge","Electric","Physical","Tough",15,90,1,-1,"User receives recoil damage."])
    movedex.append([529,"Drill Run","Ground","Physical","Tough",10,80,0.95,-1,"High critical hit ratio."])
    movedex.append([530,"Dual Chop","Dragon","Physical","Tough",15,40,0.9,-1,"Hits twice in one turn."])
    movedex.append([531,"Heart Stamp","Psychic","Physical","Cute",25,60,1,8,"May cause flinching."])
    movedex.append([532,"Horn Leech","Grass","Physical","Tough",10,75,1,-1,"User recovers half the HP inflicted on opponent."])
    movedex.append([533,"Sacred Sword","Fighting","Physical","Cool",15,90,1,-1,"Ignores opponent's stat changes."])
    movedex.append([534,"Razor Shell","Water","Physical","Cool",10,75,0.95,-1,"May lower opponent's Defense."])
    movedex.append([535,"Heat Crash","Fire","Physical","Tough",10,0,1,-1,"The heavier the user, the stronger the attack."])
    movedex.append([536,"Leaf Tornado","Grass","Special","Cool",10,65,0.9,-1,"May lower opponent's Accuracy."])
    movedex.append([537,"Steamroller","Bug","Physical","Tough",20,65,1,-1,"May cause flinching."])
    movedex.append([538,"Cotton Guard","Grass","Status","Cute",10,0,"—",-1,"Drastically raises user's Defense."])
    movedex.append([539,"Night Daze","Dark","Special","Cool",10,85,0.95,-1,"May lower opponent's Accuracy."])
    movedex.append([540,"Psystrike","Psychic","Special","Cool",10,100,1,-1,"Inflicts damage based on the target's Defense, not Special Defense."])
    movedex.append([541,"Tail Slap","Normal","Physical","Cute",10,25,0.85,-1,"Hits 2-5 times in one turn."])
    movedex.append([542,"Hurricane","Flying","Special","Tough",10,110,0.7,-1,"May confuse opponent."])
    movedex.append([543,"Head Charge","Normal","Physical","Tough",15,120,1,-1,"User receives recoil damage."])
    movedex.append([544,"Gear Grind","Steel","Physical","Clever",15,50,0.85,-1,"Hits twice in one turn."])
    movedex.append([545,"Searing Shot","Fire","Special","Cool",5,100,1,-1,"May burn opponent."])
    movedex.append([546,"Techno Blast","Normal","Special","Cool",5,120,1,-1,"Type depends on the Drive being held."])
    movedex.append([547,"Relic Song","Normal","Special","Beautiful",10,75,1,-1,"May put the target to sleep."])
    movedex.append([548,"Secret Sword","Fighting","Special","Beautiful",10,85,1,-1,"Inflicts damage based on the target's Defense, not Special Defense."])
    movedex.append([549,"Glaciate","Ice","Special","Beautiful",10,65,0.95,-1,"Lowers opponent's Speed."])
    movedex.append([550,"Bolt Strike","Electric","Physical","Beautiful",5,130,0.85,-1,"May paralyze opponent."])
    movedex.append([551,"Blue Flare","Fire","Special","Beautiful",5,130,0.85,-1,"May burn opponent."])
    movedex.append([552,"Fiery Dance","Fire","Special","Beautiful",10,80,1,-1,"May raise user's Special Attack."])
    movedex.append([553,"Freeze Shock","Ice","Physical","Beautiful",5,140,0.9,-1,"Charges on first turn, attacks on second. May paralyze opponent."])
    movedex.append([554,"Ice Burn","Ice","Special","Beautiful",5,140,0.9,-1,"Charges on first turn, attacks on second. May burn opponent."])
    movedex.append([555,"Snarl","Dark","Special","Tough",15,55,0.95,-1,"Lowers opponent's Special Attack."])
    movedex.append([556,"Icicle Crash","Ice","Physical","Beautiful",10,85,0.9,-1,"May cause flinching."])
    movedex.append([557,"V-create","Fire","Physical","Cool",5,180,0.95,-1,"Lowers user's Defense, Special Defense and Speed."])
    movedex.append([558,"Fusion Flare","Fire","Special","Beautiful",5,100,1,-1,"Power increases if Fusion Bolt is used in the same turn."])
    movedex.append([559,"Fusion Bolt","Electric","Physical","Cool",5,100,1,-1,"Power increases if Fusion Flare is used in the same turn."])
    movedex.append([560,"Flying Press","Fighting","Physical","Tough",10,100,0.95,-1,"Deals Fighting and Flying type damage."])
    movedex.append([561,"Mat Block","Fighting","Status","Cool",10,0,"—",-1,"Protects teammates from damaging moves."])
    movedex.append([562,"Belch","Poison","Special","Tough",10,120,0.9,-1,"User must have consumed a Berry."])
    movedex.append([563,"Rototiller","Ground","Status","Tough",10,0,"—",-1,"Raises Attack and Special Attack of Grass-types."])
    movedex.append([564,"Sticky Web","Bug","Status","Tough",20,0,"—",-1,"Lowers opponent's Speed when switching into battle."])
    movedex.append([565,"Fell Stinger","Bug","Physical","Cool",25,50,1,-1,"Drastically raises user's Attack if target is KO'd."])
    movedex.append([566,"Phantom Force","Ghost","Physical","Cool",10,90,1,-1,"Disappears on first turn, attacks on second. Can strike through Protect/Detect."])
    movedex.append([567,"Trick-or-Treat","Ghost","Status","Cute",20,0,1,-1,"Adds Ghost type to opponent."])
    movedex.append([568,"Noble Roar","Normal","Status","Tough",30,0,1,-1,"Lowers opponent's Attack and Special Attack."])
    movedex.append([569,"Ion Deluge","Electric","Status","Beautiful",25,0,"—",-1,"Changes Normal-type moves to Electric-type."])
    movedex.append([570,"Parabolic Charge","Electric","Special","Clever",20,65,1,-1,"User recovers half the HP inflicted on opponent."])
    movedex.append([571,"Forest's Curse","Grass","Status","Clever",20,0,1,-1,"Adds Grass type to opponent."])
    movedex.append([572,"Petal Blizzard","Grass","Physical","Beautiful",15,90,1,-1,"Hits all adjacent Pokémon."])
    movedex.append([573,"Freeze-Dry","Ice","Special","Beautiful",20,70,1,-1,"May freeze opponent. Super-effective against Water types."])
    movedex.append([574,"Disarming Voice","Fairy","Special","Cute",15,40,"—",-1,"Ignores Accuracy and Evasiveness."])
    movedex.append([575,"Parting Shot","Dark","Status","Cool",20,0,1,-1,"Lowers opponent's Attack and Special Attack then switches out."])
    movedex.append([576,"Topsy-Turvy","Dark","Status","Clever",20,0,"—",-1,"Reverses stat changes of opponent."])
    movedex.append([577,"Draining Kiss","Fairy","Special","Cute",10,50,1,-1,"User recovers most damage inflicted on opponent."])
    movedex.append([578,"Crafty Shield","Fairy","Status","Clever",10,0,"—",-1,"Protects the Pokémon from status moves."])
    movedex.append([579,"Flower Shield","Fairy","Status","Beautiful",10,0,"—",-1,"Raises Defense of all Grass-type Pokémon on the field."])
    movedex.append([580,"Grassy Terrain","Grass","Status","Beautiful",10,0,"—",-1,"Restores a little HP of all Pokémon for 5 turns."])
    movedex.append([581,"Misty Terrain","Fairy","Status","Beautiful",10,0,"—",-1,"Protects the field from status conditions for 5 turns."])
    movedex.append([582,"Electrify","Electric","Status","Clever",20,0,"—",-1,"Changes the target's move to Electric type."])
    movedex.append([583,"Play Rough","Fairy","Physical","Cute",10,90,0.9,-1,"May lower opponent's Attack."])
    movedex.append([584,"Fairy Wind","Fairy","Special","Beautiful",30,40,1,0,"A damaging attack."])
    movedex.append([585,"Moonblast","Fairy","Special","Beautiful",15,95,1,-1,"May lower opponent's Special Attack."])
    movedex.append([586,"Boomburst","Normal","Special","Tough",10,140,1,-1,"Hits all adjacent Pokémon."])
    movedex.append([587,"Fairy Lock","Fairy","Status","Clever",10,0,"—",-1,"Prevents fleeing in the next turn."])
    movedex.append([588,"King's Shield","Steel","Status","Cool",10,0,"—",-1,"Protects the user and lowers opponent's Attack on contact."])
    movedex.append([589,"Play Nice","Normal","Status","Cute",20,0,"—",-1,"Lowers opponent's Attack. Always hits."])
    movedex.append([590,"Confide","Normal","Status","Cute",20,0,"—",-1,"Lowers opponent's Special Attack."])
    movedex.append([591,"Diamond Storm","Rock","Physical","Beautiful",5,100,0.95,-1,"May raise user's Defense"])
    movedex.append([592,"Steam Eruption","Water","Special","Beautiful",5,110,0.95,-1,"May burn opponent."])
    movedex.append([593,"Hyperspace Hole","Psychic","Special","Clever",5,80,"—",-1,"Can strike through Protect/Detect."])
    movedex.append([594,"Water Shuriken","Water","Special","Cool",20,15,1,-1,"Hits 2-5 times in one turn."])
    movedex.append([595,"Mystical Fire","Fire","Special","Beautiful",10,75,1,-1,"Lowers opponent's Special Attack."])
    movedex.append([596,"Spiky Shield","Grass","Status","Tough",10,0,"—",-1,"Protects the user and inflicts damage on contact."])
    movedex.append([597,"Aromatic Mist","Fairy","Status","Beautiful",20,0,"—",-1,"Raises Special Defense of allies."])
    movedex.append([598,"Eerie Impulse","Electric","Status","Clever",15,0,1,-1,"Sharply lowers opponent's Special Attack."])
    movedex.append([599,"Venom Drench","Poison","Status","Clever",20,0,1,-1,"Lowers poisoned opponent's Special Attack and Speed."])
    movedex.append([600,"Powder","Bug","Status","Clever",20,0,1,-1,"Damages Pokémon using Fire-type moves."])
    movedex.append([601,"Geomancy","Fairy","Status","Beautiful",10,0,"—",-1,"Charges on first turn, sharply raises user's Sp. Attack, Sp. Defense and Speed on the second."])
    movedex.append([602,"Magnetic Flux","Electric","Status","Clever",20,0,"—",-1,"Raises Defense and Sp. Defense of Plus/Minus Pokémon."])
    movedex.append([603,"Happy Hour","Normal","Status","Cute",30,0,"—",7,"Doubles prize money from trainer battles."])
    movedex.append([604,"Electric Terrain","Electric","Status","Clever",10,0,"—",-1,"Prevents all Pokémon from falling asleep for 5 turns."])
    movedex.append([605,"Dazzling Gleam","Fairy","Special","Beautiful",10,80,1,-1,"Hits all adjacent opponents."])
    movedex.append([606,"Celebrate","Normal","Status","Cute",40,0,"—",-1,"The Pokémon congratulates you on your special day. No battle effect."])
    movedex.append([607,"Hold Hands","Normal","Status","Cute",40,0,"—",-1,"Makes the user and an ally very happy."])
    movedex.append([608,"Baby-Doll Eyes","Fairy","Status","Cute",30,0,1,-1,"Always goes first. Lowers the target's attack."])
    movedex.append([609,"Nuzzle","Electric","Physical","Cute",20,20,1,-1,"Paralyzes opponent."])
    movedex.append([610,"Hold Back","Normal","Physical","Cool",40,40,1,-1,"Always leaves opponent with at least 1 HP."])
    movedex.append([611,"Infestation","Bug","Special","Cute",20,20,1,-1,"Traps opponent, damaging them for 4-5 turns."])
    movedex.append([612,"Power-Up Punch","Fighting","Physical","Tough",20,40,1,-1,"Raises Attack."])
    movedex.append([613,"Oblivion Wing","Flying","Special","Cool",10,80,1,-1,"User recovers most of the HP inflicted on opponent."])
    movedex.append([614,"Thousand Arrows","Ground","Physical","Beautiful",10,90,1,-1,"Makes Flying-type Pokémon vulnerable to Ground moves."])
    movedex.append([615,"Thousand Waves","Ground","Physical","Tough",10,90,1,-1,"Opponent cannot flee or switch."])
    movedex.append([616,"Land's Wrath","Ground","Physical","Beautiful",10,90,1,0,"A damaging attack."])
    movedex.append([617,"Light of Ruin","Fairy","Special","Beautiful",5,140,0.9,-1,"User receives recoil damage."])
    movedex.append([618,"Origin Pulse","Water","Special","Beautiful",10,110,0.85,-1,"Hits all adjacent opponents."])
    movedex.append([619,"Precipice Blades","Ground","Physical","Cool",10,120,0.85,-1,"Hits all adjacent opponents."])
    movedex.append([620,"Dragon Ascent","Flying","Physical","Beautiful",5,120,1,-1,"Lowers user's Defense and Special Defense."])
    movedex.append([621,"Hyperspace Fury","Dark","Physical","Tough",5,100,"—",-1,"Lowers user's Defense. Can strike through Protect/Detect."])
    movedex.append([622,"Breakneck Blitz","Normal","Physical","???",1,0,"—",-1,"Normal type Z-Move."])
    movedex.append([623,"Breakneck Blitz","Normal","Special","???",1,0,"—",-1,"Normal type Z-Move."])
    movedex.append([624,"All-Out Pummeling","Fighting","Physical","???",1,0,"—",-1,"Fighting type Z-Move."])
    movedex.append([625,"All-Out Pummeling","Fighting","Special","???",1,0,"—",-1,"Fighting type Z-Move."])
    movedex.append([626,"Supersonic Skystrike","Flying","Physical","???",1,0,"—",-1,"Flying type Z-Move."])
    movedex.append([627,"Supersonic Skystrike","Flying","Special","???",1,0,"—",-1,"Flying type Z-Move."])
    movedex.append([628,"Acid Downpour","Poison","Physical","???",1,0,"—",-1,"Poison type Z-Move."])
    movedex.append([629,"Acid Downpour","Poison","Special","???",1,0,"—",-1,"Poison type Z-Move."])
    movedex.append([630,"Tectonic Rage","Ground","Physical","???",1,0,"—",-1,"Ground type Z-Move."])
    movedex.append([631,"Tectonic Rage","Ground","Special","???",1,0,"—",-1,"Ground type Z-Move."])
    movedex.append([632,"Continental Crush","Rock","Physical","???",1,0,"—",-1,"Rock type Z-Move."])
    movedex.append([633,"Continental Crush","Rock","Special","???",1,0,"—",-1,"Rock type Z-Move."])
    movedex.append([634,"Savage Spin-Out","Bug","Physical","???",1,0,"—",-1,"Bug type Z-Move."])
    movedex.append([635,"Savage Spin-Out","Bug","Special","???",1,0,"—",-1,"Bug type Z-Move."])
    movedex.append([636,"Never-Ending Nightmare","Ghost","Physical","???",1,0,"—",-1,"Ghost type Z-Move."])
    movedex.append([637,"Never-Ending Nightmare","Ghost","Special","???",1,0,"—",-1,"Ghost type Z-Move."])
    movedex.append([638,"Corkscrew Crash","Steel","Physical","???",1,0,"—",-1,"Steel type Z-Move."])
    movedex.append([639,"Corkscrew Crash","Steel","Special","???",1,0,"—",-1,"Steel type Z-Move."])
    movedex.append([640,"Inferno Overdrive","Fire","Physical","???",1,0,"—",-1,"Fire type Z-Move."])
    movedex.append([641,"Inferno Overdrive","Fire","Special","???",1,0,"—",-1,"Fire type Z-Move."])
    movedex.append([642,"Hydro Vortex","Water","Physical","???",1,0,"—",-1,"Water type Z-Move."])
    movedex.append([643,"Hydro Vortex","Water","Special","???",1,0,"—",-1,"Water type Z-Move."])
    movedex.append([644,"Bloom Doom","Grass","Physical","???",1,0,"—",-1,"Grass type Z-Move."])
    movedex.append([645,"Bloom Doom","Grass","Special","???",1,0,"—",-1,"Grass type Z-Move."])
    movedex.append([646,"Gigavolt Havoc","Electric","Physical","???",1,0,"—",-1,"Electric type Z-Move."])
    movedex.append([647,"Gigavolt Havoc","Electric","Special","???",1,0,"—",-1,"Electric type Z-Move."])
    movedex.append([648,"Shattered Psyche","Psychic","Physical","???",1,0,"—",-1,"Psychic type Z-Move."])
    movedex.append([649,"Shattered Psyche","Psychic","Special","???",1,0,"—",-1,"Psychic type Z-Move."])
    movedex.append([650,"Subzero Slammer","Ice","Physical","???",1,0,"—",-1,"Ice type Z-Move."])
    movedex.append([651,"Subzero Slammer","Ice","Special","???",1,0,"—",-1,"Ice type Z-Move."])
    movedex.append([652,"Devastating Drake","Dragon","Physical","???",1,0,"—",-1,"Dragon type Z-Move."])
    movedex.append([653,"Devastating Drake","Dragon","Special","???",1,0,"—",-1,"Dragon type Z-Move."])
    movedex.append([654,"Black Hole Eclipse","Dark","Physical","???",1,0,"—",-1,"Dark type Z-Move."])
    movedex.append([655,"Black Hole Eclipse","Dark","Special","???",1,0,"—",-1,"Dark type Z-Move."])
    movedex.append([656,"Twinkle Tackle","Fairy","Physical","???",1,0,"—",-1,"Fairy type Z-Move."])
    movedex.append([657,"Twinkle Tackle","Fairy","Special","???",1,0,"—",-1,"Fairy type Z-Move."])
    movedex.append([658,"Catastropika","Electric","Physical","???",1,210,"—",-1,"Pikachu-exclusive Z-Move."])
    movedex.append([659,"Shore Up","Ground","Status","???",10,0,"—",-1,"The user regains up to half of its max HP. It restores more HP in a sandstorm."])
    movedex.append([660,"First Impression","Bug","Physical","???",10,90,1,-1,"Although this move has great power, it only works the first turn the user is in battle."])
    movedex.append([661,"Baneful Bunker","Poison","Status","???",10,0,"—",-1,"Protects the user and poisons opponent on contact."])
    movedex.append([662,"Spirit Shackle","Ghost","Physical","???",10,80,1,-1,"Prevents the opponent switching out."])
    movedex.append([663,"Darkest Lariat","Dark","Physical","???",10,85,1,-1,"Ignores opponent's stat changes."])
    movedex.append([664,"Sparkling Aria","Water","Special","???",10,90,1,-1,"Heals the burns of its target."])
    movedex.append([665,"Ice Hammer","Ice","Physical","???",10,100,0.9,-1,"The user swings and hits with its strong, heavy fist. It lowers the user's Speed, however."])
    movedex.append([666,"Floral Healing","Fairy","Status","???",10,0,"—",-1,"The user restores the target's HP by up to half of its max HP. It restores more HP when the terrain is grass."])
    movedex.append([667,"High Horsepower","Ground","Physical","???",10,95,0.95,-1,"The user fiercely attacks the target using its entire body."])
    movedex.append([668,"Strength Sap","Grass","Status","???",10,0,1,-1,"The user restores its HP by the same amount as the target's Attack stat. It also lowers the target's Attack stat."])
    movedex.append([669,"Solar Blade","Grass","Physical","???",10,125,1,-1,"Charges on first turn, attacks on second."])
    movedex.append([670,"Leafage","Grass","Physical","???",40,40,1,-1,"Strikes opponent with leaves."])
    movedex.append([671,"Spotlight","Normal","Status","???",15,0,"—",-1,"The user shines a spotlight on the target so that only the target will be attacked during the turn."])
    movedex.append([672,"Toxic Thread","Poison","Status","???",20,0,1,-1,"The user shoots poisonous threads to poison the target and lower the target's Speed stat."])
    movedex.append([673,"Laser Focus","Normal","Status","???",30,0,"—",-1,"User's next attack is guaranteed to result in a critical hit."])
    movedex.append([674,"Gear Up","Steel","Status","???",20,0,"—",-1,"The user engages its gears to raise the Attack and Sp. Atk stats of ally Pokémon with the Plus or Minus Ability."])
    movedex.append([675,"Throat Chop","Dark","Physical","???",15,80,1,-1,"Prevents use of sound moves for two turns."])
    movedex.append([676,"Pollen Puff","Bug","Special","???",15,90,1,-1,"The user attacks the enemy with a pollen puff that explodes. If the target is an ally, it gives the ally a pollen puff that restores its HP instead."])
    movedex.append([677,"Anchor Shot","Steel","Physical","???",20,80,1,-1,"The user entangles the target with its anchor chain while attacking. The target becomes unable to flee."])
    movedex.append([678,"Psychic Terrain","Psychic","Status","???",10,0,"—",-1,"Prevents priority moves from being used for 5 turns."])
    movedex.append([679,"Lunge","Bug","Physical","???",15,80,1,-1,"The user makes a lunge at the target, attacking with full force. This also lowers the target's Attack stat."])
    movedex.append([680,"Fire Lash","Fire","Physical","???",15,80,1,-1,"The user strikes the target with a burning lash. This also lowers the target's Defense stat."])
    movedex.append([681,"Power Trip","Dark","Physical","???",10,20,1,-1,"The user boasts its strength and attacks the target. The more the user's stats are raised, the greater the move's power."])
    movedex.append([682,"Burn Up","Fire","Special","???",5,130,1,-1,"To inflict massive damage, the user burns itself out. After using this move, the user will no longer be Fire type."])
    movedex.append([683,"Speed Swap","Psychic","Status","???",10,0,"—",-1,"The user exchanges Speed stats with the target."])
    movedex.append([684,"Smart Strike","Steel","Physical","???",10,70,"—",-1,"The user stabs the target with a sharp horn. This attack never misses."])
    movedex.append([685,"Purify","Poison","Status","???",20,0,"—",-1,"The user heals the target's status condition. If the move succeeds, it also restores the user's own HP."])
    movedex.append([686,"Revelation Dance","Normal","Special","???",15,90,1,-1,"Type changes based on Oricorio's form."])
    movedex.append([687,"Core Enforcer","Dragon","Special","???",10,100,1,-1,"Scorches a 'Z' pattern on the ground."])
    movedex.append([688,"Trop Kick","Grass","Physical","???",15,70,1,-1,"Lowers opponent's Attack."])
    movedex.append([689,"Instruct","Psychic","Status","???",15,0,"—",-1,"Allows an ally to use a move instead."])
    movedex.append([690,"Beak Blast","Flying","Physical","???",15,100,1,-1,"The user first heats up its beak, and then it attacks the target. Making direct contact with the Pokémon while it's heating up its beak results in a burn."])
    movedex.append([691,"Clanging Scales","Dragon","Special","???",5,110,1,-1,"Lowers user's Defense."])
    movedex.append([692,"Dragon Hammer","Dragon","Physical","???",15,90,1,-1,"The user uses its body like a hammer to attack the target and inflict damage."])
    movedex.append([693,"Brutal Swing","Dark","Physical","???",20,60,1,-1,"The user swings its body around violently to inflict damage on everything in its vicinity."])
    movedex.append([694,"Aurora Veil","Ice","Status","???",20,0,"—",-1,"Halves damage from Physical and Special attacks for five turns, only in hail."])
    movedex.append([695,"Sinister Arrow Raid","Ghost","Physical","???",1,180,"—",-1,"Decidueye-exclusive Z-Move."])
    movedex.append([696,"Malicious Moonsault","Dark","Physical","???",1,180,"—",-1,"Incineroar-exclusive Z-Move."])
    movedex.append([697,"Oceanic Operetta","Water","Special","???",1,195,"—",-1,"Primarina-exclusive Z-Move."])
    movedex.append([698,"Guardian of Alola","Fairy","Special","???",1,0,"—",-1,"Tapu-exclusive Z-move. Cuts opponent's HP by 75%."])
    movedex.append([699,"Soul-Stealing 7-Star Strike","Ghost","Physical","???",1,195,"—",-1,"Marshadow-exclusive Z-Move."])
    movedex.append([700,"Stoked Sparksurfer","Electric","Special","???",1,175,"—",-1,"Alolan Raichu-exclusive Electric type Z-Move."])
    movedex.append([701,"Pulverizing Pancake","Normal","Physical","???",1,210,"—",-1,"Snorlax-exclusive Normal type Z-Move."])
    movedex.append([702,"Extreme Evoboost","Normal","Status","???",1,0,"—",-1,"Eevee-exclusive Z-Move. Sharply raises all stats."])
    movedex.append([703,"Genesis Supernova","Psychic","Special","???",1,185,"—",-1,"Mew-exclusive Z-Move."])
    movedex.append([704,"Shell Trap","Fire","Special","???",5,150,1,-1,"Deals more damage to opponent if hit by a Physical move."])
    movedex.append([705,"Fleur Cannon","Fairy","Special","???",5,130,0.9,-1,"Sharply lowers user's Special Attack."])
    movedex.append([706,"Psychic Fangs","Psychic","Physical","???",10,85,1,-1,"The user bites the target with its psychic capabilities. This can also destroy Light Screen and Reflect."])
    movedex.append([707,"Stomping Tantrum","Ground","Physical","???",10,75,1,-1,"Driven by frustration, the user attacks the target. If the user's previous move has failed, the power of this move doubles."])
    movedex.append([708,"Shadow Bone","Ghost","Physical","???",10,85,1,-1,"The user attacks by beating the target with a bone that contains a spirit. This may also lower the target's Defense stat."])
    movedex.append([709,"Accelerock","Rock","Physical","???",20,40,1,-1,"User attacks first."])
    movedex.append([710,"Liquidation","Water","Physical","???",10,85,1,-1,"The user slams into the target using a full-force blast of water. This may also lower the target's Defense stat."])
    movedex.append([711,"Prismatic Laser","Psychic","Special","???",10,160,1,-1,"The user shoots powerful lasers using the power of a prism. The user can't move on the next turn."])
    movedex.append([712,"Spectral Thief","Ghost","Physical","???",10,90,1,-1,"The user hides in the target's shadow, steals the target's stat boosts, and then attacks."])
    movedex.append([713,"Sunsteel Strike","Steel","Physical","???",5,100,1,-1,"Ignores the target's ability."])
    movedex.append([714,"Moongeist Beam","Ghost","Special","???",5,100,1,-1,"Ignores the target's ability."])
    movedex.append([715,"Tearful Look","Normal","Status","???",20,0,"—",-1,"Lowers the target's attack stats, penetrating protection."])
    movedex.append([716,"Zing Zap","Electric","Physical","???",10,80,1,-1,"A strong electric blast crashes down on the target, giving it an electric shock. This may also make the target flinch."])
    movedex.append([717,"Nature's Madness","Fairy","Special","???",10,0,0.9,-1,"Halves the foe's HP."])
    movedex.append([718,"Multi-Attack","Normal","Physical","???",10,90,1,-1,"Type matches user's current type."])
    movedex.append([719,"10,000,000 Volt Thunderbolt","Electric","Special","???",1,195,"—",-1,"Pikachu-exclusive Z-Move."])
    movedex.append([720,"Mind Blown","Fire","Special","???",5,150,1,-1,"User receives recoil damage."])
    movedex.append([721,"Plasma Fists","Electric","Physical","???",15,100,1,-1,"Changes Normal-type moves to Electric-type moves."])
    movedex.append([722,"Photon Geyser","Psychic","Special","???",5,100,1,-1,"Uses Attack or Special Attack stat, whichever is higher."])
    movedex.append([723,"Light That Burns the Sky","Psychic","Special","???",1,200,"—",-1,"Ultra Necrozma-exclusive Z-Move. Ignores target's ability; uses highest Attack stat."])
    movedex.append([724,"Searing Sunraze Smash","Steel","Special","???",1,200,"—",-1,"Solgaleo-exclusive Z-Move."])
    movedex.append([725,"Menacing Moonraze Maelstrom","Ghost","Special","???",1,200,"—",-1,"Lunala-exclusive Z-Move."])
    movedex.append([726,"Let's Snuggle Forever","Fairy","Physical","???",1,190,"—",-1,"Mimikyu-exclusive Z-Move."])
    movedex.append([727,"Splintered Stormshards","Rock","Physical","???",1,190,"—",-1,"Lycanroc-exclusive Z-Move."])
    movedex.append([728,"Clangorous Soulblaze","Dragon","Special","???",1,185,"—",-1,"Kommo-o exclusive Z-Move."])
    movedex.append([729,"Zippy Zap","Electric","Physical","???",15,50,1,-1,"High critical-hit ratio."])
    movedex.append([730,"Splishy Splash","Water","Special","???",15,90,1,-1,"May paralyze opponent."])
    movedex.append([731,"Floaty Fall","Flying","Physical","???",15,90,0.95,-1,"May cause flinching."])
    movedex.append([732,"Pika Papow","Electric","Special","???",20,0,"—",-1,"Power increases when player's bond is stronger."])
    movedex.append([733,"Bouncy Bubble","Water","Special","???",15,90,1,-1,"User recovers half the HP inflicted on opponent."])
    movedex.append([734,"Buzzy Buzz","Electric","Special","???",15,90,1,-1,"Paralyzes the opponent."])
    movedex.append([735,"Sizzly Slide","Fire","Physical","???",15,90,1,-1,"Burns the opponent."])
    movedex.append([736,"Glitzy Glow","Psychic","Special","???",15,90,1,-1,"Reduces damage from Special attacks."])
    movedex.append([737,"Baddy Bad","Dark","Special","???",15,90,1,-1,"Reduces damage from Physical attacks."])
    movedex.append([738,"Sappy Seed","Grass","Physical","???",15,90,1,-1,"Drains HP from opponent each turn."])
    movedex.append([739,"Freezy Frost","Ice","Special","???",15,90,1,-1,"Resets all stat changes."])
    movedex.append([740,"Sparkly Swirl","Fairy","Special","???",15,90,1,-1,"Cures all status problems in the party Pokémon."])
    movedex.append([741,"Veevee Volley","Normal","Physical","???",20,0,"—",-1,"Power increases when player's bond is stronger."])
    movedex.append([742,"Double Iron Bash","Steel","Physical","???",5,60,1,-1,"Hits twice in one turn; may cause flinching."])
    #OC Moves: Donut Steel
    movedex.append([743,"Chrysalize","Bug","Status","Beautiful",10,0,"—",-1,"User sleeps for 2 turns, but heals fully and increases defenses."])
    movedex.append([744,"Enshroud","Dark","Status","Clever",10,0,"—",-1,"Protects, ups evasion if the foe doesn't contact. Fails if consecutive."])
    movedex.append([745,"Legacy","Dragon","Status","Tough",10,0,1,-1,"User moves first, paralyzing and flinching foe. Only usable on first turn."])
    movedex.append([746,"Energize","Electric","Status","Clever",20,0,"—",-1,"Raises user's attack stats and next Electric move's power increases."])
    movedex.append([747,"Ardent Gaze","Fairy","Status","Cute",15,0,1,-1,"The opponent becomes less likely to attack."])
    movedex.append([748,"Disabling Poke","Fighting","Physical","Clever",30,40,1,-1,"User attacks first, disabling the foe's last used move for a few turns."])
    movedex.append([749,"Steady Flame","Fire","Status","Beautiful",10,0,1,-1,"Burns opponent."])
    movedex.append([750,"Wing It","Flying","Status","Cool",30,0,"—",-1,"Sharply raises a random stat, lowering another."])
    movedex.append([751,"Deathless","Ghost","Status","Beautiful",10,0,"—",-1,"Recovers health instead of fainting, but may fail if used consecutively."])
    movedex.append([752,"Bark Up","Grass","Status","Tough",20,0,"—",-1,"User restores HP each turn, and raises defenses, but cannot escape."])
    movedex.append([753,"Burial Ground", "Ground","Status","Clever",10,0,"—",-1,"Slows and hurts grounded non-Ground and Ghost-types for 5 turns."])
    movedex.append([754,"Slow Freeze", "Ice","Status","Cool",10,0,.6,-1,"Moves later, but freezes the foe."])
    movedex.append([755,"Simple World", "Normal","Status","Clever",10,0,"—",-1,"All grounded Pokémon become Normal-type for 5 turns."])
    movedex.append([756,"Bad Breath","Poison","Status","Tough",10,0,.90,-1,"Badly poisons opponent. If it can't, paralyzes. If it can't, confuses."])
    movedex.append([757,"Clear Mind","Psychic","Status","Clever",20,0,1,-1,"Cures all non-volatile status conditions, and resets stat changes."])
    movedex.append([758,"Splinter Shield","Rock","Status","Tough",10,0,"—",-1,"Protects, and creates rocky shards on contact. Fails if consecutive."])
    movedex.append([759,"Metallize","Steel","Status","Cool",20,0,1,-1,"Adds Steel type to a Pokémon."])
    movedex.append([760,"Healing Spring","Water","Status","Beautiful",5,0,1,-1,"Makes it rain for 5 turns, and restores a little bit of health every turn."])
    #galar/paldea moves
    movedex.append([761,"Breaking Swipe","Dragon","Physical","Tough",15,60,1,-1,"Hits adjacent opponents, lowering attack."])
    movedex.append([762,"Hyper Drill","Normal","Physical","Tough",5,100,1,-1,"Hits through protecting moves."])
    movedex.append([763,"Silk Trap","Bug","Status","Clever",10,100,1,-1,"Protects against damage, and slows foes who make contact."])
    #OC Moves: And I claim to hate Ash-Greninja
    movedex.append([764,"Liberage","Normal","Status","Cool",1,0,"-",-1,"Slays kings."])
    #galar/paldea moves:
    movedex.append([765,"Branch Poke","Grass","Physical","Tough",40,40,1,-1,"The user attacks the target by poking it with a sharply pointed branch."])
    movedex.append([766,"No Retreat","Fighting","Status","Tough",5,0,"-",-1,"Boosts all stats, but locks in. Fails if already locked in."])
    movedex.append([767,"Scale Shot","Dragon","Physical","Cool",20,25,.9,-1,"Hits 2-5 times in one turn."])
    movedex.append([768,"Headlong Rush","Ground","Physical","Tough",5,120,1,-1,"Lowers user's Defense and Special Defense."])
    movedex.append([769,"Spirit Break","Fairy","Physical","Clever",15,75,1,-1,"Lowers target's Special Attack."])
    movedex.append([770,"Flip Turn","Water","Physical","Cool",20,60,1,-1,"User switches out immediately after attacking."])
    movedex.append([771, "Aqua Cutter","Water","Physical","Cool",20,70,1,-1,"High critical rate."])
    movedex.append([772, "Fillet Away","Normal","Status","Clever",20,0,"-",-1,"Reduces health to boost stats."])
    movedex.append([773, "Salt Cure","Rock","Status","Clever",15,40,1,-1,"Does damage over time, especially to Steel/Water types."])
    movedex.append([len(movedex)+1, "Trailblaze","Grass","Physicial","Clever",20,50,1,-1,"Does damage over time, especially to Steel/Water types."])
    